# Copyright 2025 The ThunderID Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: thunderid
description: A Helm chart for ThunderID - Lightweight user and identity management system
type: application
version: 0.48.0
appVersion: "0.48.0"
