// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package coremock

import (
	"github.com/asgardeo/thunder/internal/flow/core"
	mock "github.com/stretchr/testify/mock"
)

// NewGraphCacheInterfaceMock creates a new instance of GraphCacheInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGraphCacheInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *GraphCacheInterfaceMock {
	mock := &GraphCacheInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GraphCacheInterfaceMock is an autogenerated mock type for the GraphCacheInterface type
type GraphCacheInterfaceMock struct {
	mock.Mock
}

type GraphCacheInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *GraphCacheInterfaceMock) EXPECT() *GraphCacheInterfaceMock_Expecter {
	return &GraphCacheInterfaceMock_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type GraphCacheInterfaceMock
func (_mock *GraphCacheInterfaceMock) Get(flowID string) (core.GraphInterface, bool) {
	ret := _mock.Called(flowID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 core.GraphInterface
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (core.GraphInterface, bool)); ok {
		return returnFunc(flowID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) core.GraphInterface); ok {
		r0 = returnFunc(flowID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.GraphInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(flowID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// GraphCacheInterfaceMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type GraphCacheInterfaceMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - flowID string
func (_e *GraphCacheInterfaceMock_Expecter) Get(flowID interface{}) *GraphCacheInterfaceMock_Get_Call {
	return &GraphCacheInterfaceMock_Get_Call{Call: _e.mock.On("Get", flowID)}
}

func (_c *GraphCacheInterfaceMock_Get_Call) Run(run func(flowID string)) *GraphCacheInterfaceMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GraphCacheInterfaceMock_Get_Call) Return(graphInterface core.GraphInterface, b bool) *GraphCacheInterfaceMock_Get_Call {
	_c.Call.Return(graphInterface, b)
	return _c
}

func (_c *GraphCacheInterfaceMock_Get_Call) RunAndReturn(run func(flowID string) (core.GraphInterface, bool)) *GraphCacheInterfaceMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Invalidate provides a mock function for the type GraphCacheInterfaceMock
func (_mock *GraphCacheInterfaceMock) Invalidate(flowID string) error {
	ret := _mock.Called(flowID)

	if len(ret) == 0 {
		panic("no return value specified for Invalidate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(flowID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// GraphCacheInterfaceMock_Invalidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invalidate'
type GraphCacheInterfaceMock_Invalidate_Call struct {
	*mock.Call
}

// Invalidate is a helper method to define mock.On call
//   - flowID string
func (_e *GraphCacheInterfaceMock_Expecter) Invalidate(flowID interface{}) *GraphCacheInterfaceMock_Invalidate_Call {
	return &GraphCacheInterfaceMock_Invalidate_Call{Call: _e.mock.On("Invalidate", flowID)}
}

func (_c *GraphCacheInterfaceMock_Invalidate_Call) Run(run func(flowID string)) *GraphCacheInterfaceMock_Invalidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GraphCacheInterfaceMock_Invalidate_Call) Return(err error) *GraphCacheInterfaceMock_Invalidate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *GraphCacheInterfaceMock_Invalidate_Call) RunAndReturn(run func(flowID string) error) *GraphCacheInterfaceMock_Invalidate_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type GraphCacheInterfaceMock
func (_mock *GraphCacheInterfaceMock) Set(flowID string, graph core.GraphInterface) error {
	ret := _mock.Called(flowID, graph)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, core.GraphInterface) error); ok {
		r0 = returnFunc(flowID, graph)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// GraphCacheInterfaceMock_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type GraphCacheInterfaceMock_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - flowID string
//   - graph core.GraphInterface
func (_e *GraphCacheInterfaceMock_Expecter) Set(flowID interface{}, graph interface{}) *GraphCacheInterfaceMock_Set_Call {
	return &GraphCacheInterfaceMock_Set_Call{Call: _e.mock.On("Set", flowID, graph)}
}

func (_c *GraphCacheInterfaceMock_Set_Call) Run(run func(flowID string, graph core.GraphInterface)) *GraphCacheInterfaceMock_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 core.GraphInterface
		if args[1] != nil {
			arg1 = args[1].(core.GraphInterface)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GraphCacheInterfaceMock_Set_Call) Return(err error) *GraphCacheInterfaceMock_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *GraphCacheInterfaceMock_Set_Call) RunAndReturn(run func(flowID string, graph core.GraphInterface) error) *GraphCacheInterfaceMock_Set_Call {
	_c.Call.Return(run)
	return _c
}
