// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pkimock

import (
	"crypto"
	"crypto/x509"

	mock "github.com/stretchr/testify/mock"
)

// NewPKIServiceInterfaceMock creates a new instance of PKIServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPKIServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PKIServiceInterfaceMock {
	mock := &PKIServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PKIServiceInterfaceMock is an autogenerated mock type for the PKIServiceInterface type
type PKIServiceInterfaceMock struct {
	mock.Mock
}

type PKIServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PKIServiceInterfaceMock) EXPECT() *PKIServiceInterfaceMock_Expecter {
	return &PKIServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// GetCertThumbprint provides a mock function for the type PKIServiceInterfaceMock
func (_mock *PKIServiceInterfaceMock) GetCertThumbprint(id string) string {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetCertThumbprint")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// PKIServiceInterfaceMock_GetCertThumbprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertThumbprint'
type PKIServiceInterfaceMock_GetCertThumbprint_Call struct {
	*mock.Call
}

// GetCertThumbprint is a helper method to define mock.On call
//   - id string
func (_e *PKIServiceInterfaceMock_Expecter) GetCertThumbprint(id interface{}) *PKIServiceInterfaceMock_GetCertThumbprint_Call {
	return &PKIServiceInterfaceMock_GetCertThumbprint_Call{Call: _e.mock.On("GetCertThumbprint", id)}
}

func (_c *PKIServiceInterfaceMock_GetCertThumbprint_Call) Run(run func(id string)) *PKIServiceInterfaceMock_GetCertThumbprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PKIServiceInterfaceMock_GetCertThumbprint_Call) Return(s string) *PKIServiceInterfaceMock_GetCertThumbprint_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *PKIServiceInterfaceMock_GetCertThumbprint_Call) RunAndReturn(run func(id string) string) *PKIServiceInterfaceMock_GetCertThumbprint_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrivateKey provides a mock function for the type PKIServiceInterfaceMock
func (_mock *PKIServiceInterfaceMock) GetPrivateKey(id string) (crypto.PrivateKey, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetPrivateKey")
	}

	var r0 crypto.PrivateKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (crypto.PrivateKey, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) crypto.PrivateKey); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crypto.PrivateKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PKIServiceInterfaceMock_GetPrivateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrivateKey'
type PKIServiceInterfaceMock_GetPrivateKey_Call struct {
	*mock.Call
}

// GetPrivateKey is a helper method to define mock.On call
//   - id string
func (_e *PKIServiceInterfaceMock_Expecter) GetPrivateKey(id interface{}) *PKIServiceInterfaceMock_GetPrivateKey_Call {
	return &PKIServiceInterfaceMock_GetPrivateKey_Call{Call: _e.mock.On("GetPrivateKey", id)}
}

func (_c *PKIServiceInterfaceMock_GetPrivateKey_Call) Run(run func(id string)) *PKIServiceInterfaceMock_GetPrivateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PKIServiceInterfaceMock_GetPrivateKey_Call) Return(privateKey crypto.PrivateKey, err error) *PKIServiceInterfaceMock_GetPrivateKey_Call {
	_c.Call.Return(privateKey, err)
	return _c
}

func (_c *PKIServiceInterfaceMock_GetPrivateKey_Call) RunAndReturn(run func(id string) (crypto.PrivateKey, error)) *PKIServiceInterfaceMock_GetPrivateKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetX509Certificate provides a mock function for the type PKIServiceInterfaceMock
func (_mock *PKIServiceInterfaceMock) GetX509Certificate(id string) (*x509.Certificate, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetX509Certificate")
	}

	var r0 *x509.Certificate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*x509.Certificate, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *x509.Certificate); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*x509.Certificate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PKIServiceInterfaceMock_GetX509Certificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetX509Certificate'
type PKIServiceInterfaceMock_GetX509Certificate_Call struct {
	*mock.Call
}

// GetX509Certificate is a helper method to define mock.On call
//   - id string
func (_e *PKIServiceInterfaceMock_Expecter) GetX509Certificate(id interface{}) *PKIServiceInterfaceMock_GetX509Certificate_Call {
	return &PKIServiceInterfaceMock_GetX509Certificate_Call{Call: _e.mock.On("GetX509Certificate", id)}
}

func (_c *PKIServiceInterfaceMock_GetX509Certificate_Call) Run(run func(id string)) *PKIServiceInterfaceMock_GetX509Certificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PKIServiceInterfaceMock_GetX509Certificate_Call) Return(certificate *x509.Certificate, err error) *PKIServiceInterfaceMock_GetX509Certificate_Call {
	_c.Call.Return(certificate, err)
	return _c
}

func (_c *PKIServiceInterfaceMock_GetX509Certificate_Call) RunAndReturn(run func(id string) (*x509.Certificate, error)) *PKIServiceInterfaceMock_GetX509Certificate_Call {
	_c.Call.Return(run)
	return _c
}
