# Copyright 2026 The ThunderID Authors
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    openchoreo.dev/control-plane: "true"
{{- end }}
