# Copyright 2026 The ThunderID Authors
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.project.create }}
apiVersion: openchoreo.dev/v1alpha1
kind: Project
metadata:
  name: {{ .Values.project.name }}
  annotations:
    openchoreo.dev/description: {{ .Values.project.description | quote }}
    openchoreo.dev/display-name: {{ .Values.project.displayName | quote }}
spec:
  deploymentPipelineRef:
    kind: DeploymentPipeline
    name: {{ .Values.pipelineName }}
{{- end }}

{{- if .Values.pipeline.create }}
---
apiVersion: openchoreo.dev/v1alpha1
kind: DeploymentPipeline
metadata:
  name: {{ .Values.pipelineName }}
  annotations:
    openchoreo.dev/description: "Deployment pipeline for {{ .Values.project.name }}"
    openchoreo.dev/display-name: "{{ .Values.project.name | title }} Pipeline"
spec:
  promotionPaths:
    {{- if and .Values.environments.development.create .Values.environments.staging.create }}
    - sourceEnvironmentRef:
        kind: Environment
        name: development
      targetEnvironmentRefs:
        - kind: Environment
          name: staging
    {{- end }}
    {{- if and .Values.environments.staging.create .Values.environments.production.create }}
    - sourceEnvironmentRef:
        kind: Environment
        name: staging
      targetEnvironmentRefs:
        - kind: Environment
          name: production
    {{- end }}
{{- end }}

{{- if .Values.environments.development.create }}
---
apiVersion: openchoreo.dev/v1alpha1
kind: Environment
metadata:
  name: development
  annotations:
    openchoreo.dev/description: {{ .Values.environments.development.description | quote }}
    openchoreo.dev/display-name: {{ .Values.environments.development.displayName | quote }}
spec:
  dataPlaneRef:
    kind: ClusterDataPlane
    name: {{ .Values.dataPlane.name }}
  isProduction: false
{{- end }}

{{- if .Values.environments.staging.create }}
---
apiVersion: openchoreo.dev/v1alpha1
kind: Environment
metadata:
  name: staging
  annotations:
    openchoreo.dev/description: {{ .Values.environments.staging.description | quote }}
    openchoreo.dev/display-name: {{ .Values.environments.staging.displayName | quote }}
spec:
  dataPlaneRef:
    kind: ClusterDataPlane
    name: {{ .Values.dataPlane.name }}
  isProduction: false
{{- end }}

{{- if .Values.environments.production.create }}
---
apiVersion: openchoreo.dev/v1alpha1
kind: Environment
metadata:
  name: production
  annotations:
    openchoreo.dev/description: {{ .Values.environments.production.description | quote }}
    openchoreo.dev/display-name: {{ .Values.environments.production.displayName | quote }}
spec:
  dataPlaneRef:
    kind: ClusterDataPlane
    name: {{ .Values.dataPlane.name }}
  isProduction: true
{{- end }}
