packages:
  - apps/*
  - packages/*

catalog:
  '@asgardeo/react': 0.6.17
  '@asgardeo/react-router': 1.0.17
  '@emotion/react': 11.14.0
  '@emotion/styled': 11.14.1
  '@hookform/resolvers': 5.2.2
  '@mui/material': 7.3.4
  '@mui/x-charts': 8.14.0
  '@mui/x-data-grid': 8.14.0
  '@mui/x-date-pickers': 8.14.0
  '@mui/x-tree-view': 8.14.0
  '@tanstack/react-query': 5.90.5
  '@tanstack/react-query-devtools': 5.90.2
  '@testing-library/jest-dom': 6.9.1
  '@testing-library/react': 16.3.0
  '@testing-library/user-event': 14.6.1
  '@types/node': 24.7.2
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  '@vitejs/plugin-basic-ssl': 2.1.0
  '@vitejs/plugin-react': 5.0.4
  '@vitest/coverage-istanbul': 3.2.4
  '@wso2/oxygen-ui': 0.0.1-alpha.10
  '@wso2/oxygen-ui-icons-react': 0.0.1-alpha.10
  babel-plugin-react-compiler: 19.1.0-rc.3
  clsx: 2.1.1
  dayjs: 1.11.18
  esbuild: 0.25.10
  esbuild-plugin-preserve-directives: 0.0.11
  eslint: 8.57.1
  eslint-plugin-react-refresh: 0.4.23
  glob: 11.0.3
  globals: 16.4.0
  i18next: 25.6.0
  jsdom: 27.0.1
  lucide-react: 0.545.0
  prettier: 3.6.2
  react: 19.2.3
  react-dom: 19.2.3
  react-hook-form: 7.65.0
  react-i18next: 16.0.1
  react-router: 7.9.4
  rimraf: 6.0.1
  rolldown: 1.0.0-beta.45
  rollup-plugin-visualizer: 6.0.5
  tslib: 2.8.1
  typescript: 5.9.3
  typescript-eslint: 8.45.0
  vite: npm:rolldown-vite@7.1.14
  vitest: 3.2.4
  zod: 4.1.13
