// Copyright 2026 The ThunderID Authors
// SPDX-License-Identifier: Apache-2.0

// Package nextjssdk provides MCP tools for integrating with the ThunderID Next.js SDK.
package nextjssdk

import (
	"context"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// RegisterTools registers all Next.js SDK tools with the MCP server.
func RegisterTools(server *mcp.Server) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "thunderid_integrate_nextjs_sdk",
		Description: "Provides instructions and code snippets for integrating ThunderID authentication via the " +
			"ThunderID Next.js SDK into a Next.js application (App Router). Uses ThunderID-hosted login pages " +
			"with redirect-based OAuth 2.0/OIDC flow and server-side session management via middleware.",
		Annotations: &mcp.ToolAnnotations{
			Title:          "Integrate Next.js SDK",
			IdempotentHint: true,
		},
	}, integrateNextJSSDK)
}

// integrateNextJSSDK handles the integrate_nextjs_sdk tool call.
func integrateNextJSSDK(
	ctx context.Context,
	req *mcp.CallToolRequest,
	input integrateNextJSSDKInput,
) (*mcp.CallToolResult, integrateNextJSSDKOutput, error) {
	rawInstructions := `
# ThunderID Authentication – Next.js Integration Instructions

## Project Context

This project is a **Next.js application** (App Router) that integrates **ThunderID authentication**
using the **ThunderID Next.js SDK** (~@thunderid/nextjs~). It uses ThunderID-hosted login pages with
redirect-based OAuth 2.0/OIDC flow and server-side session management.

---

## SDK & Platform

- **SDK**: @thunderid/nextjs
- **Authentication Mode**: ThunderID-hosted login (redirect-based)
- **Router**: App Router (not Pages Router)
- **Base URL**: https://localhost:8090 (or ThunderID instance URL)
- **Client ID**: <CREATED_APP'S_CLIENT_ID>

---

## Implementation Steps

### Step 1: Create a Next.js app

~~~bash
npx create-next-app@latest my-nextjs-app
cd my-nextjs-app
~~~

When prompted, select the **App Router** option (the default).

### Step 2: Install @thunderid/nextjs

~~~bash
npm install @thunderid/nextjs
~~~

### Step 3: Set environment variables

Create a ~.env.local~ file in your project root:

~~~dotenv
NEXT_PUBLIC_THUNDERID_BASE_URL=https://localhost:8090
NEXT_PUBLIC_THUNDERID_CLIENT_ID=<your-client-id>
THUNDERID_CLIENT_SECRET=<your-client-secret>
THUNDERID_SECRET=<a-random-secret-at-least-32-chars>
# DANGER: Disables ALL TLS verification. Only for local development with self-signed certs. NEVER use in production.
NODE_TLS_REJECT_UNAUTHORIZED=0
~~~

Generate a random value for ~THUNDERID_SECRET~:

~~~bash
openssl rand -base64 32
~~~

~NODE_TLS_REJECT_UNAUTHORIZED=0~ is required when ThunderID runs locally with a self-signed certificate.

### Step 4: Add ThunderIDProvider to your layout

Wrap your root layout with ~ThunderIDProvider~ from the server export:

~~~tsx
// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThunderIDProvider } from '@thunderid/nextjs/server'
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` + "`" + `${geistSans.variable} ${geistMono.variable} h-full antialiased` + "`" + `}
    >
      <body className="min-h-full flex flex-col">
        <ThunderIDProvider>{children}</ThunderIDProvider>
      </body>
    </html>
  );
}
~~~

### Step 5: Add the ThunderID proxy

Create a ~proxy.ts~ file at your project root to proxy requests through ThunderID and protect routes:

~~~ts
// proxy.ts
import {
  thunderIDProxy,
  createRouteMatcher,
} from '@thunderid/nextjs/server'

const isProtectedRoute = createRouteMatcher([
  // Add the paths you want to protect, e.g. '/dashboard(.*)'
])

export default thunderIDProxy(async (thunderid, request) => {
  if (isProtectedRoute(request)) {
    await thunderid.protectRoute()
  }
})

export const config = {
  matcher: ['/((?!_next/static|_next/image|favicon.ico).*)'],
}
~~~

### Step 6: Build with ThunderID components

Update your home page with ThunderID authentication components:

~~~tsx
// app/page.tsx
import { SignedIn, UserDropdown, SignedOut, SignInButton } from "@thunderid/nextjs";

export default function Home() {
  return (
    <section className="flex flex-col items-center justify-center min-h-screen py-2">
      <SignedIn>
        <UserDropdown />
      </SignedIn>
      <SignedOut>
        <SignInButton>Sign In</SignInButton>
      </SignedOut>
    </section>
  );
}
~~~

### Step 7: Run the app

~~~bash
npm run dev
~~~

Visit http://localhost:3000. Click **Sign In** to be redirected to the ThunderID-hosted sign-in page.

---

## CRITICAL: Import Rules

- Import ~ThunderIDProvider~ and middleware utilities from ~'@thunderid/nextjs/server'~
- Import UI components (~SignedIn~, ~SignedOut~, ~SignInButton~, ~UserDropdown~, etc.) from ~'@thunderid/nextjs'~
- The ~ThunderIDProvider~ handles the OAuth callback automatically — no manual callback route is needed
- Configuration is read from environment variables — do NOT pass config as props to the provider

---

## Render Props and Client Components

~SignInButton~ accepts a render-prop child (a function receiving ~{ signIn, isLoading }~) for custom button markup.
Because functions cannot be passed across the server/client boundary, any component using this pattern
must be a Client Component (~'use client'~ at the top of the file).

~~~tsx
'use client'
import { SignInButton } from '@thunderid/nextjs'

export default function CustomSignIn() {
  return (
    <SignInButton>
      {({ signIn, isLoading }) => (
        <button onClick={() => { void signIn?.() }} disabled={isLoading}>
          {isLoading ? 'Signing in…' : 'Sign in'}
        </button>
      )}
    </SignInButton>
  )
}
~~~

---

## Route Protection

Add paths to ~createRouteMatcher~ in ~proxy.ts~:

~~~ts
const isProtectedRoute = createRouteMatcher([
  '/dashboard(.*)',
  '/profile(.*)',
])
~~~

---

## References

- [ThunderID Next.js SDK Docs](/docs/next/sdks/nextjs/overview)
- [ThunderIDProvider Configuration](/docs/next/sdks/nextjs/apis/contexts/thunderid-provider)
- [SDK Components](/docs/next/sdks/nextjs/apis/components/sign-in-button)
`
	instructions := strings.ReplaceAll(rawInstructions, "~", "`")

	snippets := `
import { ThunderIDProvider } from '@thunderid/nextjs/server';

// Root layout
<ThunderIDProvider>{children}</ThunderIDProvider>

// Home page
import { SignedIn, UserDropdown, SignedOut, SignInButton } from "@thunderid/nextjs";

<SignedIn><UserDropdown /></SignedIn>
<SignedOut><SignInButton>Sign In</SignInButton></SignedOut>
`

	if input.ServerURL != "" {
		instructions = strings.ReplaceAll(instructions, "https://localhost:8090", input.ServerURL)
		snippets = strings.ReplaceAll(snippets, "https://localhost:8090", input.ServerURL)
	}

	return nil, integrateNextJSSDKOutput{
		Instructions: instructions,
		CodeSnippets: snippets,
	}, nil
}
