title: "[Design Discussion] "
labels: ["Type/Design"]
body:
  - type: input
    id: feature_issue
    attributes:
      label: Related Feature Issue
      description: Link to the approved feature issue this design addresses
      placeholder: "#123 or https://github.com/asgardeo/thunder/issues/<>"
    validations:
      required: true

  - type: textarea
    id: problem_recap
    attributes:
      label: Problem Summary
      description: Brief summary of the problem we're solving (2-3 sentences). This helps readers understand context without navigating to the feature issue.
      placeholder: |
        Enterprise customers with existing LDAP directories (1000+ users) cannot efficiently 
        onboard users into Thunder. This design proposes an LDAP synchronization system that 
        automatically provisions users from LDAP directories.
    validations:
      required: true
      
  - type: textarea
    id: high_level_approach
    attributes:
      label: High-Level Approach
      description: |
        Describe HOW you plan to solve the problem. Focus on the technical approach, not the problem itself (that's already in the feature issue).
      placeholder: |
        - Add LDAP connector service that queries LDAP servers
        - Create scheduled sync job (configurable interval)
        - Map LDAP attributes to Thunder user fields
        - Provide admin UI for LDAP configuration
        - Support read-only sync initially (LDAP → Thunder)
    validations:
      required: true
        
  - type: textarea
    id: architecture
    attributes:
      label: Architecture Overview
      description: Describe new components, services, and how they integrate with existing Thunder architecture
      placeholder: |
        Components:
        - LDAP Connector Service: Queries LDAP, transforms data
        - Sync Scheduler: Triggers periodic synchronization
        - User Provisioning Service: Creates/updates Thunder users
        - Admin UI: Configuration interface

        [Optional: Include diagrams or links to diagrams]
    validations:
      required: true
        
  - type: textarea
    id: security
    attributes:
      label: Security Considerations
      description: Security implications and how you plan to address them
      placeholder: |
        - LDAP credentials stored encrypted at rest
        - Support for LDAPS (LDAP over TLS)
        - Rate limiting on sync operations
        - Audit logging of all provisioning events
    validations:
      required: true

  - type: textarea
    id: impact_areas
    attributes:
      label: Impacted Areas
      description: List Thunder components or areas that will be affected
      placeholder: |
        - User Management
        - Authentication
        - Admin Dashboard
        - API Layer
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other approaches you considered and why you chose this one
      placeholder: |
        **Alternative 1**: Real-time sync via webhooks
        - Pros: Immediate synchronization
        - Cons: Not supported by all LDAP servers, complex to implement
        - Decision: Use scheduled sync for v1, consider real-time for v2

        **Alternative 2**: Bidirectional sync
        - Pros: Changes in Thunder reflected in LDAP
        - Cons: Complex conflict resolution, risky
        - Decision: Read-only for v1, bidirectional as separate feature
    validations:
      required: true

  - type: textarea
    id: discussion_points
    attributes:
      label: Questions for Community Input
      description: Technical questions, trade-offs, or areas where you need community feedback
      placeholder: |
        1. Should we support multiple LDAP servers per organization?
        2. How do we handle users who exist in both LDAP and Thunder?
        3. What's the right sync frequency? (Hourly? Daily? Configurable?)
        4. Should this be a core feature or an optional plugin?
        5. How do we handle deleted users in LDAP?
    validations:
      required: false
