title: "[Design Discussion] "
labels: ["Type/Design", "Status/Discussion"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Issue
        
  - type: input
    id: feature_issue
    attributes:
      label: Related Feature Issue
      description: Link to the feature issue this design addresses
      placeholder: "#123 or https://github.com/asgardeo/thunder/issues/<>"
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |
        ---
        ## Problem Recap
        
  - type: textarea
    id: problem_recap
    attributes:
      label: Problem Summary
      description: Brief summary of the problem we're solving (2-3 sentences)
      placeholder: |
        Example:
        Enterprise customers with existing LDAP directories (1000+ users) cannot efficiently 
        onboard users into Thunder. This design proposes an LDAP synchronization system that 
        automatically provisions users from LDAP directories.
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |
        ---
        ## High-Level Approach
        
  - type: textarea
    id: high_level_approach
    attributes:
      label: Proposed Approach
      description: Describe your proposed approach at a high level
      placeholder: |
        Example:
        - Add LDAP connector service that queries LDAP servers
        - Create scheduled sync job (configurable interval)
        - Map LDAP attributes to Thunder user fields
        - Provide admin UI for LDAP configuration
        - Support read-only sync initially (LDAP → Thunder)
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |
        ---
        ## Key Design Questions
        
  - type: textarea
    id: design_questions
    attributes:
      label: Technical Questions for Discussion
      description: List the main technical questions that need community input
      placeholder: |
        Example:
        1. Should we support multiple LDAP servers per organization?
        2. How do we handle users who exist in both LDAP and Thunder?
        3. What's the right sync frequency? (Hourly? Daily? Configurable?)
        4. Which LDAP attributes should we map by default?
        5. How do we handle deleted users in LDAP?
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |
        ---
        ## Alternative Approaches Considered
        
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Approaches
      description: List alternatives you considered and why you chose this approach
      placeholder: |
        Example:
        **Alternative 1**: Real-time sync via webhooks
        - Pros: Immediate synchronization
        - Cons: Not supported by all LDAP servers, complex to implement
        - Decision: Use scheduled sync for v1, consider real-time for v2

        **Alternative 2**: Bidirectional sync
        - Pros: Changes in Thunder reflected in LDAP
        - Cons: Complex conflict resolution, risky
        - Decision: Read-only for v1, bidirectional as separate feature
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |
        ---
        ## Architecture Overview
        
  - type: textarea
    id: architecture
    attributes:
      label: Architecture and Components
      description: High-level architecture description or component overview
      placeholder: |
        Example:
        Components:
        - LDAP Connector Service: Queries LDAP, transforms data
        - Sync Scheduler: Triggers periodic synchronization
        - User Provisioning Service: Creates/updates Thunder users
        - Admin UI: Configuration interface

        [Optional: Include diagrams or links to diagrams]
    validations:
      required: false
      
  - type: markdown
    attributes:
      value: |
        ---
        ## Security Considerations
        
  - type: textarea
    id: security
    attributes:
      label: Security Considerations
      description: Initial thoughts on security implications (will be detailed in formal proposal)
      placeholder: |
        Example:
        - LDAP credentials stored encrypted at rest
        - Support for LDAPS (LDAP over TLS)
        - Rate limiting on sync operations
        - Audit logging of all provisioning events
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |
        ---
        ## Implementation Considerations
        
  - type: dropdown
    id: complexity
    attributes:
      label: Implementation Complexity
      description: How complex do you estimate this implementation to be?
      options:
        - Low (1-2 weeks)
        - Medium (3-6 weeks)
        - High (2-3 months)
        - Very High (3+ months)
    validations:
      required: true
      
  - type: textarea
    id: impact_areas
    attributes:
      label: Areas of Thunder that will be impacted
      description: List all areas that this design will affect
      placeholder: |
        Example:
        - User Management
        - Authentication
        - Admin Dashboard
        - API Layer
    validations:
      required: true
        
  - type: markdown
    attributes:
      value: |
        ---
        ## Open Questions
        
  - type: textarea
    id: open_questions
    attributes:
      label: Questions for Community Input
      description: What specific aspects do you need community feedback on?
      placeholder: |
        Example:
        - Should we support LDAP groups mapping to Thunder roles?
        - How do we handle schema differences across LDAP implementations?
        - What's the rollback strategy if sync fails midway?
        - Should this be a core feature or an optional plugin?
    validations:
      required: false
