-- Table to store generic runtime key-value entries, partitioned by NAMESPACE.
CREATE TABLE "RUNTIME_STORE" (
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    NAMESPACE     VARCHAR(64)  NOT NULL,
    KEY           VARCHAR(512) NOT NULL,
    VALUE         JSONB        NOT NULL,
    EXPIRY_TIME   TIMESTAMP,
    CREATED_AT    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (DEPLOYMENT_ID, NAMESPACE, KEY)
) PARTITION BY LIST (NAMESPACE);

-- One child partition per providers.RuntimeStoreNamespace constant.
-- Adding a new namespace constant REQUIRES adding a matching partition here.
CREATE TABLE "RUNTIME_STORE_ATTRIBUTE_CACHE" PARTITION OF "RUNTIME_STORE" FOR VALUES IN ('attribute:cache');
CREATE TABLE "RUNTIME_STORE_FLOW_STATE" PARTITION OF "RUNTIME_STORE" FOR VALUES IN ('flow:state');
CREATE TABLE "RUNTIME_STORE_AUTHZ_CODE" PARTITION OF "RUNTIME_STORE" FOR VALUES IN ('authz:code');
CREATE TABLE "RUNTIME_STORE_AUTHZ_REQ"  PARTITION OF "RUNTIME_STORE" FOR VALUES IN ('authz:req');
CREATE TABLE "RUNTIME_STORE_LOGOUT_REQ" PARTITION OF "RUNTIME_STORE" FOR VALUES IN ('logout:req');
CREATE TABLE "RUNTIME_STORE_PAR_REQ"    PARTITION OF "RUNTIME_STORE" FOR VALUES IN ('par:req');
CREATE TABLE "RUNTIME_STORE_CIBA_REQ"   PARTITION OF "RUNTIME_STORE" FOR VALUES IN ('ciba:req');
CREATE TABLE "RUNTIME_STORE_JTI_TOKEN"  PARTITION OF "RUNTIME_STORE" FOR VALUES IN ('jti:token');
CREATE TABLE "RUNTIME_STORE_VCI_NONCE"  PARTITION OF "RUNTIME_STORE" FOR VALUES IN ('vci:nonce');
CREATE TABLE "RUNTIME_STORE_VCI_OFFER"  PARTITION OF "RUNTIME_STORE" FOR VALUES IN ('vci:offer');
CREATE TABLE "RUNTIME_STORE_VP_STATE"   PARTITION OF "RUNTIME_STORE" FOR VALUES IN ('vp:state');
CREATE TABLE "RUNTIME_STORE_WEBAUTHN_SESSION" PARTITION OF "RUNTIME_STORE" FOR VALUES IN ('webauthn:session');

-- Index for expiry time on RUNTIME_STORE (propagates to all partitions; supports cleanup and expiry checks)
CREATE INDEX idx_runtime_store_expiry_time ON "RUNTIME_STORE" (EXPIRY_TIME);
