-- Table to store Organization Units
CREATE TABLE ORGANIZATION_UNIT (
    ID              INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPLOYMENT_ID       VARCHAR(255) NOT NULL,
    OU_ID           VARCHAR(36) NOT NULL,
    PARENT_ID       VARCHAR(36),
    HANDLE          VARCHAR(100)        NOT NULL,
    NAME            VARCHAR(100)        NOT NULL,
    DESCRIPTION     VARCHAR(255),
    CREATED_AT      TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT      TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (OU_ID, DEPLOYMENT_ID),
    FOREIGN KEY (PARENT_ID, DEPLOYMENT_ID) REFERENCES ORGANIZATION_UNIT (OU_ID, DEPLOYMENT_ID) ON DELETE CASCADE
);

-- Index for deployment isolation on ORGANIZATION_UNIT
CREATE INDEX idx_organization_unit_deployment_id ON ORGANIZATION_UNIT (DEPLOYMENT_ID);

-- Table to store Users
CREATE TABLE "USER" (
    ID          INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPLOYMENT_ID   VARCHAR(255) NOT NULL,
    USER_ID     VARCHAR(36)        NOT NULL,
    OU_ID       VARCHAR(36)        NOT NULL,
    TYPE        VARCHAR(50)        NOT NULL,
    ATTRIBUTES  JSONB,
    CREDENTIALS JSONB,
    CREATED_AT  TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT  TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (USER_ID, DEPLOYMENT_ID)
);

-- Index for deployment isolation on USER
CREATE INDEX idx_user_deployment_id ON "USER" (DEPLOYMENT_ID);

-- Table to store Groups
CREATE TABLE "GROUP" (
    ID              INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPLOYMENT_ID       VARCHAR(255) NOT NULL,
    GROUP_ID        VARCHAR(36)        NOT NULL,
    OU_ID           VARCHAR(36)        NOT NULL,
    NAME            VARCHAR(50)        NOT NULL,
    DESCRIPTION     VARCHAR(255),
    CREATED_AT      TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT      TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (GROUP_ID, DEPLOYMENT_ID)
);

-- Index for deployment isolation on GROUP
CREATE INDEX idx_group_deployment_id ON "GROUP" (DEPLOYMENT_ID);

-- Table to store Group member assignments
CREATE TABLE GROUP_MEMBER_REFERENCE (
    ID          INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPLOYMENT_ID   VARCHAR(255) NOT NULL,
    GROUP_ID    VARCHAR(36) NOT NULL,
    MEMBER_TYPE VARCHAR(7)  NOT NULL,
    MEMBER_ID   VARCHAR(36) NOT NULL,
    CREATED_AT  TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT  TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (GROUP_ID, DEPLOYMENT_ID) REFERENCES "GROUP" (GROUP_ID, DEPLOYMENT_ID) ON DELETE CASCADE
);

-- Index for deployment isolation on GROUP_MEMBER_REFERENCE
CREATE INDEX idx_group_member_reference_deployment_id ON GROUP_MEMBER_REFERENCE (DEPLOYMENT_ID);
