-- Table to store OAuth2 authorization codes.
CREATE TABLE AUTHORIZATION_CODE (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODE_ID VARCHAR(36) UNIQUE NOT NULL,
    AUTHORIZATION_CODE VARCHAR(500) NOT NULL,
    CLIENT_ID VARCHAR(255) NOT NULL,
    STATE VARCHAR(50) NOT NULL,
    AUTHZ_DATA JSONB NOT NULL,
    TIME_CREATED TIMESTAMP NOT NULL,
    EXPIRY_TIME TIMESTAMP NOT NULL
);

-- Table to store flow context metadata and state
CREATE TABLE FLOW_CONTEXT (
    FLOW_ID VARCHAR(36) PRIMARY KEY,
    APP_ID VARCHAR(36) NOT NULL,
    CURRENT_NODE_ID VARCHAR(50),
    CURRENT_ACTION_ID VARCHAR(50),
    GRAPH_ID VARCHAR(50) NOT NULL,
    RUNTIME_DATA JSONB,
    EXECUTION_HISTORY JSONB,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Table to store flow user data
CREATE TABLE FLOW_USER_DATA (
    FLOW_ID VARCHAR(36) PRIMARY KEY REFERENCES FLOW_CONTEXT(FLOW_ID) ON DELETE CASCADE,
    IS_AUTHENTICATED BOOLEAN NOT NULL DEFAULT FALSE,
    USER_ID VARCHAR(36),
    OU_ID VARCHAR(36),
    USER_TYPE VARCHAR(50),
    USER_INPUTS JSONB,
    USER_ATTRIBUTES JSONB,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
