// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package enginemock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewAuthorizationEngineMock creates a new instance of AuthorizationEngineMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorizationEngineMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthorizationEngineMock {
	mock := &AuthorizationEngineMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthorizationEngineMock is an autogenerated mock type for the AuthorizationEngine type
type AuthorizationEngineMock struct {
	mock.Mock
}

type AuthorizationEngineMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthorizationEngineMock) EXPECT() *AuthorizationEngineMock_Expecter {
	return &AuthorizationEngineMock_Expecter{mock: &_m.Mock}
}

// GetAuthorizedPermissions provides a mock function for the type AuthorizationEngineMock
func (_mock *AuthorizationEngineMock) GetAuthorizedPermissions(userID string, groupIDs []string, requestedPermissions []string) ([]string, error) {
	ret := _mock.Called(userID, groupIDs, requestedPermissions)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorizedPermissions")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []string, []string) ([]string, error)); ok {
		return returnFunc(userID, groupIDs, requestedPermissions)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []string, []string) []string); ok {
		r0 = returnFunc(userID, groupIDs, requestedPermissions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []string, []string) error); ok {
		r1 = returnFunc(userID, groupIDs, requestedPermissions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthorizationEngineMock_GetAuthorizedPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorizedPermissions'
type AuthorizationEngineMock_GetAuthorizedPermissions_Call struct {
	*mock.Call
}

// GetAuthorizedPermissions is a helper method to define mock.On call
//   - userID string
//   - groupIDs []string
//   - requestedPermissions []string
func (_e *AuthorizationEngineMock_Expecter) GetAuthorizedPermissions(userID interface{}, groupIDs interface{}, requestedPermissions interface{}) *AuthorizationEngineMock_GetAuthorizedPermissions_Call {
	return &AuthorizationEngineMock_GetAuthorizedPermissions_Call{Call: _e.mock.On("GetAuthorizedPermissions", userID, groupIDs, requestedPermissions)}
}

func (_c *AuthorizationEngineMock_GetAuthorizedPermissions_Call) Run(run func(userID string, groupIDs []string, requestedPermissions []string)) *AuthorizationEngineMock_GetAuthorizedPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthorizationEngineMock_GetAuthorizedPermissions_Call) Return(strings []string, err error) *AuthorizationEngineMock_GetAuthorizedPermissions_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *AuthorizationEngineMock_GetAuthorizedPermissions_Call) RunAndReturn(run func(userID string, groupIDs []string, requestedPermissions []string) ([]string, error)) *AuthorizationEngineMock_GetAuthorizedPermissions_Call {
	_c.Call.Return(run)
	return _c
}
