// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package flowexecmock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/pkg/thunderidengine/common"
	"github.com/thunder-id/thunderid/pkg/thunderidengine/providers"
)

// newFlowDefaultsProviderMock creates a new instance of flowDefaultsProviderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newFlowDefaultsProviderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *flowDefaultsProviderMock {
	mock := &flowDefaultsProviderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// flowDefaultsProviderMock is an autogenerated mock type for the flowDefaultsProvider type
type flowDefaultsProviderMock struct {
	mock.Mock
}

type flowDefaultsProviderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *flowDefaultsProviderMock) EXPECT() *flowDefaultsProviderMock_Expecter {
	return &flowDefaultsProviderMock_Expecter{mock: &_m.Mock}
}

// GetFlowExpirySeconds provides a mock function for the type flowDefaultsProviderMock
func (_mock *flowDefaultsProviderMock) GetFlowExpirySeconds(ctx context.Context, flowType providers.FlowType) int64 {
	ret := _mock.Called(ctx, flowType)

	if len(ret) == 0 {
		panic("no return value specified for GetFlowExpirySeconds")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func(context.Context, providers.FlowType) int64); ok {
		r0 = returnFunc(ctx, flowType)
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// flowDefaultsProviderMock_GetFlowExpirySeconds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlowExpirySeconds'
type flowDefaultsProviderMock_GetFlowExpirySeconds_Call struct {
	*mock.Call
}

// GetFlowExpirySeconds is a helper method to define mock.On call
//   - ctx context.Context
//   - flowType providers.FlowType
func (_e *flowDefaultsProviderMock_Expecter) GetFlowExpirySeconds(ctx interface{}, flowType interface{}) *flowDefaultsProviderMock_GetFlowExpirySeconds_Call {
	return &flowDefaultsProviderMock_GetFlowExpirySeconds_Call{Call: _e.mock.On("GetFlowExpirySeconds", ctx, flowType)}
}

func (_c *flowDefaultsProviderMock_GetFlowExpirySeconds_Call) Run(run func(ctx context.Context, flowType providers.FlowType)) *flowDefaultsProviderMock_GetFlowExpirySeconds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 providers.FlowType
		if args[1] != nil {
			arg1 = args[1].(providers.FlowType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *flowDefaultsProviderMock_GetFlowExpirySeconds_Call) Return(n int64) *flowDefaultsProviderMock_GetFlowExpirySeconds_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *flowDefaultsProviderMock_GetFlowExpirySeconds_Call) RunAndReturn(run func(ctx context.Context, flowType providers.FlowType) int64) *flowDefaultsProviderMock_GetFlowExpirySeconds_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveDefaultFlowHandle provides a mock function for the type flowDefaultsProviderMock
func (_mock *flowDefaultsProviderMock) ResolveDefaultFlowHandle(ctx context.Context, flowType providers.FlowType) (string, *common.ServiceError) {
	ret := _mock.Called(ctx, flowType)

	if len(ret) == 0 {
		panic("no return value specified for ResolveDefaultFlowHandle")
	}

	var r0 string
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, providers.FlowType) (string, *common.ServiceError)); ok {
		return returnFunc(ctx, flowType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, providers.FlowType) string); ok {
		r0 = returnFunc(ctx, flowType)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, providers.FlowType) *common.ServiceError); ok {
		r1 = returnFunc(ctx, flowType)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// flowDefaultsProviderMock_ResolveDefaultFlowHandle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveDefaultFlowHandle'
type flowDefaultsProviderMock_ResolveDefaultFlowHandle_Call struct {
	*mock.Call
}

// ResolveDefaultFlowHandle is a helper method to define mock.On call
//   - ctx context.Context
//   - flowType providers.FlowType
func (_e *flowDefaultsProviderMock_Expecter) ResolveDefaultFlowHandle(ctx interface{}, flowType interface{}) *flowDefaultsProviderMock_ResolveDefaultFlowHandle_Call {
	return &flowDefaultsProviderMock_ResolveDefaultFlowHandle_Call{Call: _e.mock.On("ResolveDefaultFlowHandle", ctx, flowType)}
}

func (_c *flowDefaultsProviderMock_ResolveDefaultFlowHandle_Call) Run(run func(ctx context.Context, flowType providers.FlowType)) *flowDefaultsProviderMock_ResolveDefaultFlowHandle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 providers.FlowType
		if args[1] != nil {
			arg1 = args[1].(providers.FlowType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *flowDefaultsProviderMock_ResolveDefaultFlowHandle_Call) Return(s string, serviceError *common.ServiceError) *flowDefaultsProviderMock_ResolveDefaultFlowHandle_Call {
	_c.Call.Return(s, serviceError)
	return _c
}

func (_c *flowDefaultsProviderMock_ResolveDefaultFlowHandle_Call) RunAndReturn(run func(ctx context.Context, flowType providers.FlowType) (string, *common.ServiceError)) *flowDefaultsProviderMock_ResolveDefaultFlowHandle_Call {
	_c.Call.Return(run)
	return _c
}
