// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package messagemock

import (
	"github.com/asgardeo/thunder/internal/notification/common"
	mock "github.com/stretchr/testify/mock"
)

// NewMessageClientInterfaceMock creates a new instance of MessageClientInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageClientInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageClientInterfaceMock {
	mock := &MessageClientInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MessageClientInterfaceMock is an autogenerated mock type for the MessageClientInterface type
type MessageClientInterfaceMock struct {
	mock.Mock
}

type MessageClientInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageClientInterfaceMock) EXPECT() *MessageClientInterfaceMock_Expecter {
	return &MessageClientInterfaceMock_Expecter{mock: &_m.Mock}
}

// GetName provides a mock function for the type MessageClientInterfaceMock
func (_mock *MessageClientInterfaceMock) GetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MessageClientInterfaceMock_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MessageClientInterfaceMock_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MessageClientInterfaceMock_Expecter) GetName() *MessageClientInterfaceMock_GetName_Call {
	return &MessageClientInterfaceMock_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *MessageClientInterfaceMock_GetName_Call) Run(run func()) *MessageClientInterfaceMock_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MessageClientInterfaceMock_GetName_Call) Return(s string) *MessageClientInterfaceMock_GetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MessageClientInterfaceMock_GetName_Call) RunAndReturn(run func() string) *MessageClientInterfaceMock_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// SendSMS provides a mock function for the type MessageClientInterfaceMock
func (_mock *MessageClientInterfaceMock) SendSMS(sms common.SMSData) error {
	ret := _mock.Called(sms)

	if len(ret) == 0 {
		panic("no return value specified for SendSMS")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(common.SMSData) error); ok {
		r0 = returnFunc(sms)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MessageClientInterfaceMock_SendSMS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendSMS'
type MessageClientInterfaceMock_SendSMS_Call struct {
	*mock.Call
}

// SendSMS is a helper method to define mock.On call
//   - sms common.SMSData
func (_e *MessageClientInterfaceMock_Expecter) SendSMS(sms interface{}) *MessageClientInterfaceMock_SendSMS_Call {
	return &MessageClientInterfaceMock_SendSMS_Call{Call: _e.mock.On("SendSMS", sms)}
}

func (_c *MessageClientInterfaceMock_SendSMS_Call) Run(run func(sms common.SMSData)) *MessageClientInterfaceMock_SendSMS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 common.SMSData
		if args[0] != nil {
			arg0 = args[0].(common.SMSData)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MessageClientInterfaceMock_SendSMS_Call) Return(err error) *MessageClientInterfaceMock_SendSMS_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MessageClientInterfaceMock_SendSMS_Call) RunAndReturn(run func(sms common.SMSData) error) *MessageClientInterfaceMock_SendSMS_Call {
	_c.Call.Return(run)
	return _c
}
