// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package passkeymock

import (
	"github.com/asgardeo/thunder/internal/authn/common"
	"github.com/asgardeo/thunder/internal/authn/passkey"
	"github.com/asgardeo/thunder/internal/system/error/serviceerror"
	mock "github.com/stretchr/testify/mock"
)

// NewWebAuthnAuthnServiceInterfaceMock creates a new instance of WebAuthnAuthnServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWebAuthnAuthnServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *WebAuthnAuthnServiceInterfaceMock {
	mock := &WebAuthnAuthnServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WebAuthnAuthnServiceInterfaceMock is an autogenerated mock type for the PasskeyServiceInterface type
type WebAuthnAuthnServiceInterfaceMock struct {
	mock.Mock
}

type WebAuthnAuthnServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *WebAuthnAuthnServiceInterfaceMock) EXPECT() *WebAuthnAuthnServiceInterfaceMock_Expecter {
	return &WebAuthnAuthnServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// FinishAuthentication provides a mock function for the type WebAuthnAuthnServiceInterfaceMock
func (_mock *WebAuthnAuthnServiceInterfaceMock) FinishAuthentication(req *passkey.PasskeyAuthenticationFinishRequest) (*common.AuthenticationResponse, *serviceerror.ServiceError) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for FinishAuthentication")
	}

	var r0 *common.AuthenticationResponse
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(*passkey.PasskeyAuthenticationFinishRequest) (*common.AuthenticationResponse, *serviceerror.ServiceError)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(*passkey.PasskeyAuthenticationFinishRequest) *common.AuthenticationResponse); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.AuthenticationResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*passkey.PasskeyAuthenticationFinishRequest) *serviceerror.ServiceError); ok {
		r1 = returnFunc(req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// WebAuthnAuthnServiceInterfaceMock_FinishAuthentication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishAuthentication'
type WebAuthnAuthnServiceInterfaceMock_FinishAuthentication_Call struct {
	*mock.Call
}

// FinishAuthentication is a helper method to define mock.On call
//   - req *passkey.PasskeyAuthenticationFinishRequest
func (_e *WebAuthnAuthnServiceInterfaceMock_Expecter) FinishAuthentication(req interface{}) *WebAuthnAuthnServiceInterfaceMock_FinishAuthentication_Call {
	return &WebAuthnAuthnServiceInterfaceMock_FinishAuthentication_Call{Call: _e.mock.On("FinishAuthentication", req)}
}

func (_c *WebAuthnAuthnServiceInterfaceMock_FinishAuthentication_Call) Run(run func(req *passkey.PasskeyAuthenticationFinishRequest)) *WebAuthnAuthnServiceInterfaceMock_FinishAuthentication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *passkey.PasskeyAuthenticationFinishRequest
		if args[0] != nil {
			arg0 = args[0].(*passkey.PasskeyAuthenticationFinishRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WebAuthnAuthnServiceInterfaceMock_FinishAuthentication_Call) Return(authenticationResponse *common.AuthenticationResponse, serviceError *serviceerror.ServiceError) *WebAuthnAuthnServiceInterfaceMock_FinishAuthentication_Call {
	_c.Call.Return(authenticationResponse, serviceError)
	return _c
}

func (_c *WebAuthnAuthnServiceInterfaceMock_FinishAuthentication_Call) RunAndReturn(run func(req *passkey.PasskeyAuthenticationFinishRequest) (*common.AuthenticationResponse, *serviceerror.ServiceError)) *WebAuthnAuthnServiceInterfaceMock_FinishAuthentication_Call {
	_c.Call.Return(run)
	return _c
}

// FinishRegistration provides a mock function for the type WebAuthnAuthnServiceInterfaceMock
func (_mock *WebAuthnAuthnServiceInterfaceMock) FinishRegistration(req *passkey.PasskeyRegistrationFinishRequest) (*passkey.PasskeyRegistrationFinishData, *serviceerror.ServiceError) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for FinishRegistration")
	}

	var r0 *passkey.PasskeyRegistrationFinishData
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(*passkey.PasskeyRegistrationFinishRequest) (*passkey.PasskeyRegistrationFinishData, *serviceerror.ServiceError)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(*passkey.PasskeyRegistrationFinishRequest) *passkey.PasskeyRegistrationFinishData); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*passkey.PasskeyRegistrationFinishData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*passkey.PasskeyRegistrationFinishRequest) *serviceerror.ServiceError); ok {
		r1 = returnFunc(req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// WebAuthnAuthnServiceInterfaceMock_FinishRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishRegistration'
type WebAuthnAuthnServiceInterfaceMock_FinishRegistration_Call struct {
	*mock.Call
}

// FinishRegistration is a helper method to define mock.On call
//   - req *passkey.PasskeyRegistrationFinishRequest
func (_e *WebAuthnAuthnServiceInterfaceMock_Expecter) FinishRegistration(req interface{}) *WebAuthnAuthnServiceInterfaceMock_FinishRegistration_Call {
	return &WebAuthnAuthnServiceInterfaceMock_FinishRegistration_Call{Call: _e.mock.On("FinishRegistration", req)}
}

func (_c *WebAuthnAuthnServiceInterfaceMock_FinishRegistration_Call) Run(run func(req *passkey.PasskeyRegistrationFinishRequest)) *WebAuthnAuthnServiceInterfaceMock_FinishRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *passkey.PasskeyRegistrationFinishRequest
		if args[0] != nil {
			arg0 = args[0].(*passkey.PasskeyRegistrationFinishRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WebAuthnAuthnServiceInterfaceMock_FinishRegistration_Call) Return(passkeyRegistrationFinishData *passkey.PasskeyRegistrationFinishData, serviceError *serviceerror.ServiceError) *WebAuthnAuthnServiceInterfaceMock_FinishRegistration_Call {
	_c.Call.Return(passkeyRegistrationFinishData, serviceError)
	return _c
}

func (_c *WebAuthnAuthnServiceInterfaceMock_FinishRegistration_Call) RunAndReturn(run func(req *passkey.PasskeyRegistrationFinishRequest) (*passkey.PasskeyRegistrationFinishData, *serviceerror.ServiceError)) *WebAuthnAuthnServiceInterfaceMock_FinishRegistration_Call {
	_c.Call.Return(run)
	return _c
}

// StartAuthentication provides a mock function for the type WebAuthnAuthnServiceInterfaceMock
func (_mock *WebAuthnAuthnServiceInterfaceMock) StartAuthentication(req *passkey.PasskeyAuthenticationStartRequest) (*passkey.PasskeyAuthenticationStartData, *serviceerror.ServiceError) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for StartAuthentication")
	}

	var r0 *passkey.PasskeyAuthenticationStartData
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(*passkey.PasskeyAuthenticationStartRequest) (*passkey.PasskeyAuthenticationStartData, *serviceerror.ServiceError)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(*passkey.PasskeyAuthenticationStartRequest) *passkey.PasskeyAuthenticationStartData); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*passkey.PasskeyAuthenticationStartData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*passkey.PasskeyAuthenticationStartRequest) *serviceerror.ServiceError); ok {
		r1 = returnFunc(req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// WebAuthnAuthnServiceInterfaceMock_StartAuthentication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartAuthentication'
type WebAuthnAuthnServiceInterfaceMock_StartAuthentication_Call struct {
	*mock.Call
}

// StartAuthentication is a helper method to define mock.On call
//   - req *passkey.PasskeyAuthenticationStartRequest
func (_e *WebAuthnAuthnServiceInterfaceMock_Expecter) StartAuthentication(req interface{}) *WebAuthnAuthnServiceInterfaceMock_StartAuthentication_Call {
	return &WebAuthnAuthnServiceInterfaceMock_StartAuthentication_Call{Call: _e.mock.On("StartAuthentication", req)}
}

func (_c *WebAuthnAuthnServiceInterfaceMock_StartAuthentication_Call) Run(run func(req *passkey.PasskeyAuthenticationStartRequest)) *WebAuthnAuthnServiceInterfaceMock_StartAuthentication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *passkey.PasskeyAuthenticationStartRequest
		if args[0] != nil {
			arg0 = args[0].(*passkey.PasskeyAuthenticationStartRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WebAuthnAuthnServiceInterfaceMock_StartAuthentication_Call) Return(passkeyAuthenticationStartData *passkey.PasskeyAuthenticationStartData, serviceError *serviceerror.ServiceError) *WebAuthnAuthnServiceInterfaceMock_StartAuthentication_Call {
	_c.Call.Return(passkeyAuthenticationStartData, serviceError)
	return _c
}

func (_c *WebAuthnAuthnServiceInterfaceMock_StartAuthentication_Call) RunAndReturn(run func(req *passkey.PasskeyAuthenticationStartRequest) (*passkey.PasskeyAuthenticationStartData, *serviceerror.ServiceError)) *WebAuthnAuthnServiceInterfaceMock_StartAuthentication_Call {
	_c.Call.Return(run)
	return _c
}

// StartRegistration provides a mock function for the type WebAuthnAuthnServiceInterfaceMock
func (_mock *WebAuthnAuthnServiceInterfaceMock) StartRegistration(req *passkey.PasskeyRegistrationStartRequest) (*passkey.PasskeyRegistrationStartData, *serviceerror.ServiceError) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for StartRegistration")
	}

	var r0 *passkey.PasskeyRegistrationStartData
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(*passkey.PasskeyRegistrationStartRequest) (*passkey.PasskeyRegistrationStartData, *serviceerror.ServiceError)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(*passkey.PasskeyRegistrationStartRequest) *passkey.PasskeyRegistrationStartData); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*passkey.PasskeyRegistrationStartData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*passkey.PasskeyRegistrationStartRequest) *serviceerror.ServiceError); ok {
		r1 = returnFunc(req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// WebAuthnAuthnServiceInterfaceMock_StartRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartRegistration'
type WebAuthnAuthnServiceInterfaceMock_StartRegistration_Call struct {
	*mock.Call
}

// StartRegistration is a helper method to define mock.On call
//   - req *passkey.PasskeyRegistrationStartRequest
func (_e *WebAuthnAuthnServiceInterfaceMock_Expecter) StartRegistration(req interface{}) *WebAuthnAuthnServiceInterfaceMock_StartRegistration_Call {
	return &WebAuthnAuthnServiceInterfaceMock_StartRegistration_Call{Call: _e.mock.On("StartRegistration", req)}
}

func (_c *WebAuthnAuthnServiceInterfaceMock_StartRegistration_Call) Run(run func(req *passkey.PasskeyRegistrationStartRequest)) *WebAuthnAuthnServiceInterfaceMock_StartRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *passkey.PasskeyRegistrationStartRequest
		if args[0] != nil {
			arg0 = args[0].(*passkey.PasskeyRegistrationStartRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WebAuthnAuthnServiceInterfaceMock_StartRegistration_Call) Return(passkeyRegistrationStartData *passkey.PasskeyRegistrationStartData, serviceError *serviceerror.ServiceError) *WebAuthnAuthnServiceInterfaceMock_StartRegistration_Call {
	_c.Call.Return(passkeyRegistrationStartData, serviceError)
	return _c
}

func (_c *WebAuthnAuthnServiceInterfaceMock_StartRegistration_Call) RunAndReturn(run func(req *passkey.PasskeyRegistrationStartRequest) (*passkey.PasskeyRegistrationStartData, *serviceerror.ServiceError)) *WebAuthnAuthnServiceInterfaceMock_StartRegistration_Call {
	_c.Call.Return(run)
	return _c
}
