// Code generated by mockery v2.53.3. DO NOT EDIT.

package authzmock

import (
	authz "github.com/asgardeo/thunder/internal/oauth/oauth2/authz"
	mock "github.com/stretchr/testify/mock"
)

// AuthorizeServiceInterfaceMock is an autogenerated mock type for the AuthorizeServiceInterface type
type AuthorizeServiceInterfaceMock struct {
	mock.Mock
}

type AuthorizeServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthorizeServiceInterfaceMock) EXPECT() *AuthorizeServiceInterfaceMock_Expecter {
	return &AuthorizeServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// GetAuthorizationCodeDetails provides a mock function with given fields: clientID, code
func (_m *AuthorizeServiceInterfaceMock) GetAuthorizationCodeDetails(clientID string, code string) (*authz.AuthorizationCode, error) {
	ret := _m.Called(clientID, code)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorizationCodeDetails")
	}

	var r0 *authz.AuthorizationCode
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*authz.AuthorizationCode, error)); ok {
		return rf(clientID, code)
	}
	if rf, ok := ret.Get(0).(func(string, string) *authz.AuthorizationCode); ok {
		r0 = rf(clientID, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authz.AuthorizationCode)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(clientID, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthorizeServiceInterfaceMock_GetAuthorizationCodeDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorizationCodeDetails'
type AuthorizeServiceInterfaceMock_GetAuthorizationCodeDetails_Call struct {
	*mock.Call
}

// GetAuthorizationCodeDetails is a helper method to define mock.On call
//   - clientID string
//   - code string
func (_e *AuthorizeServiceInterfaceMock_Expecter) GetAuthorizationCodeDetails(clientID interface{}, code interface{}) *AuthorizeServiceInterfaceMock_GetAuthorizationCodeDetails_Call {
	return &AuthorizeServiceInterfaceMock_GetAuthorizationCodeDetails_Call{Call: _e.mock.On("GetAuthorizationCodeDetails", clientID, code)}
}

func (_c *AuthorizeServiceInterfaceMock_GetAuthorizationCodeDetails_Call) Run(run func(clientID string, code string)) *AuthorizeServiceInterfaceMock_GetAuthorizationCodeDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *AuthorizeServiceInterfaceMock_GetAuthorizationCodeDetails_Call) Return(_a0 *authz.AuthorizationCode, _a1 error) *AuthorizeServiceInterfaceMock_GetAuthorizationCodeDetails_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthorizeServiceInterfaceMock_GetAuthorizationCodeDetails_Call) RunAndReturn(run func(string, string) (*authz.AuthorizationCode, error)) *AuthorizeServiceInterfaceMock_GetAuthorizationCodeDetails_Call {
	_c.Call.Return(run)
	return _c
}

// HandleAuthorizationCallback provides a mock function with given fields: authID, assertion
func (_m *AuthorizeServiceInterfaceMock) HandleAuthorizationCallback(authID string, assertion string) (string, *authz.AuthorizationError) {
	ret := _m.Called(authID, assertion)

	if len(ret) == 0 {
		panic("no return value specified for HandleAuthorizationCallback")
	}

	var r0 string
	var r1 *authz.AuthorizationError
	if rf, ok := ret.Get(0).(func(string, string) (string, *authz.AuthorizationError)); ok {
		return rf(authID, assertion)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(authID, assertion)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) *authz.AuthorizationError); ok {
		r1 = rf(authID, assertion)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*authz.AuthorizationError)
		}
	}

	return r0, r1
}

// AuthorizeServiceInterfaceMock_HandleAuthorizationCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleAuthorizationCallback'
type AuthorizeServiceInterfaceMock_HandleAuthorizationCallback_Call struct {
	*mock.Call
}

// HandleAuthorizationCallback is a helper method to define mock.On call
//   - authID string
//   - assertion string
func (_e *AuthorizeServiceInterfaceMock_Expecter) HandleAuthorizationCallback(authID interface{}, assertion interface{}) *AuthorizeServiceInterfaceMock_HandleAuthorizationCallback_Call {
	return &AuthorizeServiceInterfaceMock_HandleAuthorizationCallback_Call{Call: _e.mock.On("HandleAuthorizationCallback", authID, assertion)}
}

func (_c *AuthorizeServiceInterfaceMock_HandleAuthorizationCallback_Call) Run(run func(authID string, assertion string)) *AuthorizeServiceInterfaceMock_HandleAuthorizationCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *AuthorizeServiceInterfaceMock_HandleAuthorizationCallback_Call) Return(_a0 string, _a1 *authz.AuthorizationError) *AuthorizeServiceInterfaceMock_HandleAuthorizationCallback_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthorizeServiceInterfaceMock_HandleAuthorizationCallback_Call) RunAndReturn(run func(string, string) (string, *authz.AuthorizationError)) *AuthorizeServiceInterfaceMock_HandleAuthorizationCallback_Call {
	_c.Call.Return(run)
	return _c
}

// HandleInitialAuthorizationRequest provides a mock function with given fields: msg
func (_m *AuthorizeServiceInterfaceMock) HandleInitialAuthorizationRequest(msg *authz.OAuthMessage) (*authz.AuthorizationInitResult, *authz.AuthorizationError) {
	ret := _m.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for HandleInitialAuthorizationRequest")
	}

	var r0 *authz.AuthorizationInitResult
	var r1 *authz.AuthorizationError
	if rf, ok := ret.Get(0).(func(*authz.OAuthMessage) (*authz.AuthorizationInitResult, *authz.AuthorizationError)); ok {
		return rf(msg)
	}
	if rf, ok := ret.Get(0).(func(*authz.OAuthMessage) *authz.AuthorizationInitResult); ok {
		r0 = rf(msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authz.AuthorizationInitResult)
		}
	}

	if rf, ok := ret.Get(1).(func(*authz.OAuthMessage) *authz.AuthorizationError); ok {
		r1 = rf(msg)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*authz.AuthorizationError)
		}
	}

	return r0, r1
}

// AuthorizeServiceInterfaceMock_HandleInitialAuthorizationRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleInitialAuthorizationRequest'
type AuthorizeServiceInterfaceMock_HandleInitialAuthorizationRequest_Call struct {
	*mock.Call
}

// HandleInitialAuthorizationRequest is a helper method to define mock.On call
//   - msg *authz.OAuthMessage
func (_e *AuthorizeServiceInterfaceMock_Expecter) HandleInitialAuthorizationRequest(msg interface{}) *AuthorizeServiceInterfaceMock_HandleInitialAuthorizationRequest_Call {
	return &AuthorizeServiceInterfaceMock_HandleInitialAuthorizationRequest_Call{Call: _e.mock.On("HandleInitialAuthorizationRequest", msg)}
}

func (_c *AuthorizeServiceInterfaceMock_HandleInitialAuthorizationRequest_Call) Run(run func(msg *authz.OAuthMessage)) *AuthorizeServiceInterfaceMock_HandleInitialAuthorizationRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*authz.OAuthMessage))
	})
	return _c
}

func (_c *AuthorizeServiceInterfaceMock_HandleInitialAuthorizationRequest_Call) Return(_a0 *authz.AuthorizationInitResult, _a1 *authz.AuthorizationError) *AuthorizeServiceInterfaceMock_HandleInitialAuthorizationRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthorizeServiceInterfaceMock_HandleInitialAuthorizationRequest_Call) RunAndReturn(run func(*authz.OAuthMessage) (*authz.AuthorizationInitResult, *authz.AuthorizationError)) *AuthorizeServiceInterfaceMock_HandleInitialAuthorizationRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthorizeServiceInterfaceMock creates a new instance of AuthorizeServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorizeServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthorizeServiceInterfaceMock {
	mock := &AuthorizeServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
