-- Table to store User Schemas
CREATE TABLE USER_SCHEMAS (
    ID          INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPLOYMENT_ID   VARCHAR(255) NOT NULL,
    SCHEMA_ID   VARCHAR(36) NOT NULL,
    NAME        VARCHAR(100) NOT NULL,
    OU_ID       VARCHAR(36) NOT NULL,
    ALLOW_SELF_REGISTRATION BOOLEAN DEFAULT FALSE NOT NULL,
    SCHEMA_DEF  JSONB NOT NULL,
    CREATED_AT  TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT  TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (SCHEMA_ID, DEPLOYMENT_ID),
    UNIQUE (NAME, DEPLOYMENT_ID)
);

-- Index for deployment isolation on USER_SCHEMAS
CREATE INDEX idx_user_schemas_deployment_id ON USER_SCHEMAS (DEPLOYMENT_ID);

-- Table to store Roles
CREATE TABLE "ROLE" (
    ID                  INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPLOYMENT_ID           VARCHAR(255) NOT NULL,
    ROLE_ID             VARCHAR(36) NOT NULL,
    OU_ID               VARCHAR(36) NOT NULL,
    NAME                VARCHAR(50) NOT NULL,
    DESCRIPTION         VARCHAR(255),
    CREATED_AT          TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT          TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (ROLE_ID, DEPLOYMENT_ID),
    CONSTRAINT unique_role_ou_name UNIQUE (OU_ID, NAME, DEPLOYMENT_ID)
);

-- Index for deployment isolation on ROLE
CREATE INDEX idx_role_deployment_id ON "ROLE" (DEPLOYMENT_ID);

-- Table to store Role permissions
CREATE TABLE ROLE_PERMISSION (
    ID                  INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPLOYMENT_ID       VARCHAR(255) NOT NULL,
    ROLE_ID             VARCHAR(36) NOT NULL,
    RESOURCE_SERVER_ID  VARCHAR(36) NOT NULL,
    PERMISSION          VARCHAR(100) NOT NULL,
    CREATED_AT          TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (ROLE_ID, DEPLOYMENT_ID) REFERENCES "ROLE" (ROLE_ID, DEPLOYMENT_ID) ON DELETE CASCADE,
    CONSTRAINT unique_role_permission UNIQUE (ROLE_ID, RESOURCE_SERVER_ID, PERMISSION, DEPLOYMENT_ID)
);


-- Index for resource server queries with deployment isolation on ROLE_PERMISSION
CREATE INDEX idx_role_permission_resource_server ON ROLE_PERMISSION (RESOURCE_SERVER_ID, DEPLOYMENT_ID);


-- Table to store Role assignments (to users and groups)
CREATE TABLE ROLE_ASSIGNMENT (
    ID              INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPLOYMENT_ID       VARCHAR(255) NOT NULL,
    ROLE_ID         VARCHAR(36) NOT NULL,
    ASSIGNEE_TYPE   VARCHAR(5)  NOT NULL CHECK (ASSIGNEE_TYPE IN ('user', 'group')),
    ASSIGNEE_ID     VARCHAR(36) NOT NULL,
    CREATED_AT      TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT      TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (ROLE_ID, DEPLOYMENT_ID) REFERENCES "ROLE" (ROLE_ID, DEPLOYMENT_ID) ON DELETE CASCADE,
    CONSTRAINT unique_role_assignment UNIQUE (ROLE_ID, ASSIGNEE_TYPE, ASSIGNEE_ID, DEPLOYMENT_ID)
);

-- Index for deployment isolation on ROLE_ASSIGNMENT
CREATE INDEX idx_role_assignment_deployment_id ON ROLE_ASSIGNMENT (DEPLOYMENT_ID);

-- Indexes for authorization queries

-- Index for finding all roles assigned to a specific assignee
CREATE INDEX idx_role_assignment_assignee
ON ROLE_ASSIGNMENT (ASSIGNEE_ID, ASSIGNEE_TYPE);

-- Index for finding all permissions for a specific role
CREATE INDEX idx_role_permission_role
ON ROLE_PERMISSION (ROLE_ID);

-- Table to store branding configurations.
CREATE TABLE BRANDING (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    BRANDING_ID VARCHAR(36) NOT NULL,
    DISPLAY_NAME VARCHAR(255) NOT NULL,
    PREFERENCES JSONB NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (BRANDING_ID, DEPLOYMENT_ID)
);

-- Index for deployment isolation on BRANDING
CREATE INDEX idx_branding_deployment_id ON BRANDING (DEPLOYMENT_ID);

-- Table to store basic service provider (app) details.
CREATE TABLE SP_APP (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    APP_ID VARCHAR(36) NOT NULL,
    APP_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    AUTH_FLOW_GRAPH_ID VARCHAR(100) NOT NULL,
    REGISTRATION_FLOW_GRAPH_ID VARCHAR(100) NOT NULL,
    IS_REGISTRATION_FLOW_ENABLED CHAR(1) DEFAULT '1',
    BRANDING_ID VARCHAR(36),
    APP_JSON JSONB,
    UNIQUE (APP_ID, DEPLOYMENT_ID),
    FOREIGN KEY (BRANDING_ID, DEPLOYMENT_ID) REFERENCES BRANDING(BRANDING_ID, DEPLOYMENT_ID) ON DELETE RESTRICT
);

-- Index for deployment isolation on SP_APP
CREATE INDEX idx_sp_app_deployment_id ON SP_APP (DEPLOYMENT_ID);

-- Index for efficient lookups of applications by branding.
CREATE INDEX idx_sp_app_branding_id ON SP_APP(BRANDING_ID);

-- Table to store OAuth configurations for SP apps.
CREATE TABLE IDN_OAUTH_CONSUMER_APPS (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    CONSUMER_KEY VARCHAR(255) NOT NULL,
    CONSUMER_SECRET VARCHAR(255) NOT NULL,
    APP_ID VARCHAR(36) NOT NULL,
    OAUTH_CONFIG_JSON JSONB,
    FOREIGN KEY (APP_ID, DEPLOYMENT_ID) REFERENCES SP_APP(APP_ID, DEPLOYMENT_ID) ON DELETE CASCADE
);

-- Index for deployment isolation on IDN_OAUTH_CONSUMER_APPS
CREATE INDEX idx_idn_oauth_consumer_apps_deployment_id ON IDN_OAUTH_CONSUMER_APPS (DEPLOYMENT_ID);

-- Table to store inbound auth configs (e.g., OAuth, SAML) for SP apps.
CREATE TABLE SP_INBOUND_AUTH (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    INBOUND_AUTH_KEY VARCHAR(255) NOT NULL,
    INBOUND_AUTH_TYPE VARCHAR(50) NOT NULL,
    APP_ID VARCHAR(36) NOT NULL,
    FOREIGN KEY (APP_ID, DEPLOYMENT_ID) REFERENCES SP_APP(APP_ID, DEPLOYMENT_ID) ON DELETE CASCADE
);

-- Index for deployment isolation on SP_INBOUND_AUTH
CREATE INDEX idx_sp_inbound_auth_deployment_id ON SP_INBOUND_AUTH (DEPLOYMENT_ID);

-- Table to store identity providers.
CREATE TABLE IDP (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    IDP_ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(500),
    TYPE VARCHAR(20) NOT NULL,
    PROPERTIES JSONB,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (IDP_ID, DEPLOYMENT_ID)
);

-- Index for deployment isolation on IDP
CREATE INDEX idx_idp_deployment_id ON IDP (DEPLOYMENT_ID);

-- Table to store notification senders.
CREATE TABLE NOTIFICATION_SENDER (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    SENDER_ID VARCHAR(36) NOT NULL,
    DESCRIPTION VARCHAR(500),
    TYPE VARCHAR(20) NOT NULL,
    PROVIDER VARCHAR(20) NOT NULL,
    PROPERTIES JSONB,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (SENDER_ID, DEPLOYMENT_ID)
);

-- Index for deployment isolation on NOTIFICATION_SENDER
CREATE INDEX idx_notification_sender_deployment_id ON NOTIFICATION_SENDER (DEPLOYMENT_ID);

-- Table to store certificates associated with various entities.
CREATE TABLE CERTIFICATE (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    CERT_ID VARCHAR(36) NOT NULL,
    REF_TYPE VARCHAR(20) NOT NULL,
    REF_ID VARCHAR(36) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    VALUE TEXT NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (CERT_ID, DEPLOYMENT_ID),
    UNIQUE (REF_TYPE, REF_ID, DEPLOYMENT_ID)
);

-- Index for deployment isolation on CERTIFICATE
CREATE INDEX idx_certificate_deployment_id ON CERTIFICATE (DEPLOYMENT_ID);

-- Table to store resource servers.
CREATE TABLE RESOURCE_SERVER (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    RESOURCE_SERVER_ID VARCHAR(36) NOT NULL,
    OU_ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    IDENTIFIER VARCHAR(100),
    PROPERTIES JSONB,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (RESOURCE_SERVER_ID, DEPLOYMENT_ID),
    UNIQUE (OU_ID, NAME, DEPLOYMENT_ID),
    UNIQUE (ID, DEPLOYMENT_ID)
);

-- Index for deployment isolation on RESOURCE_SERVER
CREATE INDEX idx_resource_server_deployment_id ON RESOURCE_SERVER (DEPLOYMENT_ID);

-- Unique constraint: Resource server identifier must be unique per deployment (when not null)
CREATE UNIQUE INDEX uq_resource_server_identifier
    ON RESOURCE_SERVER(IDENTIFIER, DEPLOYMENT_ID)
    WHERE IDENTIFIER IS NOT NULL;

-- Table to store resources within resource servers.
CREATE TABLE RESOURCE (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    RESOURCE_ID VARCHAR(36) NOT NULL,
    RESOURCE_SERVER_ID INT NOT NULL,
    PARENT_RESOURCE_ID INT,
    NAME VARCHAR(100) NOT NULL,
    HANDLE VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    PERMISSION VARCHAR(1000) NOT NULL,
    PROPERTIES JSONB,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (RESOURCE_ID, DEPLOYMENT_ID),
    UNIQUE (ID, DEPLOYMENT_ID),

    FOREIGN KEY (RESOURCE_SERVER_ID, DEPLOYMENT_ID)
        REFERENCES RESOURCE_SERVER(ID, DEPLOYMENT_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    FOREIGN KEY (PARENT_RESOURCE_ID, DEPLOYMENT_ID)
        REFERENCES RESOURCE(ID, DEPLOYMENT_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

-- Index for deployment isolation on RESOURCE
CREATE INDEX idx_resource_deployment_id ON RESOURCE (DEPLOYMENT_ID);

-- Unique constraint: Resource handle must be unique under the same parent per deployment
CREATE UNIQUE INDEX uq_resource_handle_with_parent
    ON RESOURCE(RESOURCE_SERVER_ID, PARENT_RESOURCE_ID, HANDLE, DEPLOYMENT_ID)
    WHERE PARENT_RESOURCE_ID IS NOT NULL;

-- Unique constraint: Root-level resource handles must be unique per resource server per deployment
CREATE UNIQUE INDEX uq_resource_handle_null_parent
    ON RESOURCE(RESOURCE_SERVER_ID, HANDLE, DEPLOYMENT_ID)
    WHERE PARENT_RESOURCE_ID IS NULL;

-- Table to store actions at resource server or resource level.
CREATE TABLE ACTION (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    ACTION_ID VARCHAR(36) NOT NULL,
    RESOURCE_SERVER_ID INT NOT NULL,
    RESOURCE_ID INT,
    NAME VARCHAR(100) NOT NULL,
    HANDLE VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    PERMISSION VARCHAR(1000) NOT NULL,
    PROPERTIES JSONB,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (ACTION_ID, DEPLOYMENT_ID),

    FOREIGN KEY (RESOURCE_SERVER_ID, DEPLOYMENT_ID)
        REFERENCES RESOURCE_SERVER(ID, DEPLOYMENT_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    FOREIGN KEY (RESOURCE_ID, DEPLOYMENT_ID)
        REFERENCES RESOURCE(ID, DEPLOYMENT_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

-- Index for deployment isolation on ACTION
CREATE INDEX idx_action_deployment_id ON ACTION (DEPLOYMENT_ID);

-- Unique constraint: Server-level action handles must be unique per resource server per deployment
CREATE UNIQUE INDEX uq_action_server_handle
    ON ACTION(RESOURCE_SERVER_ID, HANDLE, DEPLOYMENT_ID)
    WHERE RESOURCE_ID IS NULL;

-- Unique constraint: Resource-level action handles must be unique per resource per deployment
CREATE UNIQUE INDEX uq_action_resource_handle
    ON ACTION(RESOURCE_ID, HANDLE, DEPLOYMENT_ID)
    WHERE RESOURCE_ID IS NOT NULL;

-- Table to store active flow definitions
CREATE TABLE FLOW (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    FLOW_ID VARCHAR(36) NOT NULL,
    HANDLE VARCHAR(100) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    FLOW_TYPE VARCHAR(50) NOT NULL,
    ACTIVE_VERSION INTEGER NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (FLOW_ID, DEPLOYMENT_ID),
    UNIQUE (ID, DEPLOYMENT_ID),
    UNIQUE (HANDLE, FLOW_TYPE, DEPLOYMENT_ID)
);

-- Index for deployment isolation on FLOW
CREATE INDEX idx_flow_deployment_id ON FLOW (DEPLOYMENT_ID);

-- Index for flow type on FLOW
CREATE INDEX idx_flow_type ON FLOW (FLOW_TYPE);

-- Table to store flow version history
CREATE TABLE FLOW_VERSION (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    FLOW_INTERNAL_ID INTEGER NOT NULL,
    VERSION INTEGER NOT NULL,
    NODES JSONB NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (FLOW_INTERNAL_ID, VERSION, DEPLOYMENT_ID),
    UNIQUE (ID, DEPLOYMENT_ID),
    FOREIGN KEY (FLOW_INTERNAL_ID, DEPLOYMENT_ID) 
        REFERENCES FLOW(ID, DEPLOYMENT_ID) 
        ON DELETE CASCADE
);

-- Index for deployment isolation on FLOW_VERSION
CREATE INDEX idx_flow_version_deployment_id ON FLOW_VERSION (DEPLOYMENT_ID);

-- Index for flow lookup on FLOW_VERSION
CREATE INDEX idx_flow_version_flow_internal_id ON FLOW_VERSION (FLOW_INTERNAL_ID, DEPLOYMENT_ID);

-- Table to store i18n translations
CREATE TABLE TRANSLATION (
    ID              INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPLOYMENT_ID   VARCHAR(255) NOT NULL,
    MESSAGE_KEY     VARCHAR(255) NOT NULL,
    LANGUAGE_CODE   VARCHAR(10) NOT NULL,
    NAMESPACE       VARCHAR(50) NOT NULL DEFAULT 'default',
    VALUE           TEXT NOT NULL,
    CREATED_AT      TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT      TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_translation_key_lang_ns UNIQUE (MESSAGE_KEY, LANGUAGE_CODE, NAMESPACE, DEPLOYMENT_ID)
);

-- Index for efficient language-based lookups
CREATE INDEX idx_translation_language ON TRANSLATION (DEPLOYMENT_ID, LANGUAGE_CODE);

-- Index for efficient key-based lookups
CREATE INDEX idx_translation_key ON TRANSLATION (DEPLOYMENT_ID, MESSAGE_KEY);

-- Index for efficient namespace-based lookups
CREATE INDEX idx_translation_namespace ON TRANSLATION (DEPLOYMENT_ID, NAMESPACE);

-- Index for efficient language and namespace combination lookups
CREATE INDEX idx_translation_lang_namespace ON TRANSLATION (DEPLOYMENT_ID, LANGUAGE_CODE, NAMESPACE);
