-- Table to store User Schemas
CREATE TABLE USER_SCHEMAS (
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    DEPLOYMENT_ID   VARCHAR(255) NOT NULL,
    SCHEMA_ID   VARCHAR(36) NOT NULL,
    NAME        VARCHAR(100) NOT NULL,
    OU_ID       VARCHAR(36) NOT NULL,
    ALLOW_SELF_REGISTRATION INTEGER NOT NULL DEFAULT 0,
    SCHEMA_DEF  TEXT NOT NULL,
    CREATED_AT  TEXT DEFAULT (datetime('now')),
    UPDATED_AT  TEXT DEFAULT (datetime('now')),
    UNIQUE (SCHEMA_ID, DEPLOYMENT_ID),
    UNIQUE (NAME, DEPLOYMENT_ID)
);

-- Index for deployment isolation on USER_SCHEMAS
CREATE INDEX idx_user_schemas_deployment_id ON USER_SCHEMAS (DEPLOYMENT_ID);

-- Table to store Roles
CREATE TABLE "ROLE" (
    ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
    DEPLOYMENT_ID           VARCHAR(255) NOT NULL,
    ROLE_ID             VARCHAR(36) NOT NULL,
    OU_ID               VARCHAR(36) NOT NULL,
    NAME                VARCHAR(50) NOT NULL,
    DESCRIPTION         VARCHAR(255),
    CREATED_AT          TEXT DEFAULT (datetime('now')),
    UPDATED_AT          TEXT DEFAULT (datetime('now')),
    UNIQUE (ROLE_ID, DEPLOYMENT_ID),
    CONSTRAINT unique_role_ou_name UNIQUE (OU_ID, NAME, DEPLOYMENT_ID)
);

-- Index for deployment isolation on ROLE
CREATE INDEX idx_role_deployment_id ON "ROLE" (DEPLOYMENT_ID);

-- Table to store Role permissions
CREATE TABLE ROLE_PERMISSION (
    ID              INTEGER PRIMARY KEY AUTOINCREMENT,
    DEPLOYMENT_ID       VARCHAR(255) NOT NULL,
    ROLE_ID         VARCHAR(36) NOT NULL,
    PERMISSION      VARCHAR(100) NOT NULL,
    CREATED_AT      TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (ROLE_ID, DEPLOYMENT_ID) REFERENCES "ROLE" (ROLE_ID, DEPLOYMENT_ID) ON DELETE CASCADE,
    CONSTRAINT unique_role_permission UNIQUE (ROLE_ID, PERMISSION, DEPLOYMENT_ID)
);

-- Index for deployment isolation on ROLE_PERMISSION
CREATE INDEX idx_role_permission_deployment_id ON ROLE_PERMISSION (DEPLOYMENT_ID);

-- Table to store Role assignments (to users and groups)
CREATE TABLE ROLE_ASSIGNMENT (
    ID              INTEGER PRIMARY KEY AUTOINCREMENT,
    DEPLOYMENT_ID       VARCHAR(255) NOT NULL,
    ROLE_ID         VARCHAR(36) NOT NULL,
    ASSIGNEE_TYPE   VARCHAR(5)  NOT NULL CHECK (ASSIGNEE_TYPE IN ('user', 'group')),
    ASSIGNEE_ID     VARCHAR(36) NOT NULL,
    CREATED_AT      TEXT DEFAULT (datetime('now')),
    UPDATED_AT      TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (ROLE_ID, DEPLOYMENT_ID) REFERENCES "ROLE" (ROLE_ID, DEPLOYMENT_ID) ON DELETE CASCADE,
    CONSTRAINT unique_role_assignment UNIQUE (ROLE_ID, ASSIGNEE_TYPE, ASSIGNEE_ID, DEPLOYMENT_ID)
);

-- Index for deployment isolation on ROLE_ASSIGNMENT
CREATE INDEX idx_role_assignment_deployment_id ON ROLE_ASSIGNMENT (DEPLOYMENT_ID);

-- Indexes for authorization queries

-- Index for finding all roles assigned to a specific assignee
CREATE INDEX idx_role_assignment_assignee
ON ROLE_ASSIGNMENT (ASSIGNEE_ID, ASSIGNEE_TYPE);

-- Index for finding all permissions for a specific role
CREATE INDEX idx_role_permission_role
ON ROLE_PERMISSION (ROLE_ID);

-- Table to store branding configurations.
CREATE TABLE BRANDING (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    BRANDING_ID VARCHAR(36) NOT NULL,
    DISPLAY_NAME VARCHAR(255) NOT NULL,
    PREFERENCES TEXT NOT NULL,
    CREATED_AT TEXT DEFAULT (datetime('now')),
    UPDATED_AT TEXT DEFAULT (datetime('now')),
    UNIQUE (BRANDING_ID, DEPLOYMENT_ID)
);

-- Index for deployment isolation on BRANDING
CREATE INDEX idx_branding_deployment_id ON BRANDING (DEPLOYMENT_ID);

-- Table to store basic service provider (app) details.
CREATE TABLE SP_APP (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    APP_ID VARCHAR(36) NOT NULL,
    APP_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    AUTH_FLOW_GRAPH_ID VARCHAR(100) NOT NULL,
    REGISTRATION_FLOW_GRAPH_ID VARCHAR(100) NOT NULL,
    IS_REGISTRATION_FLOW_ENABLED CHAR(1) DEFAULT '1',
    BRANDING_ID VARCHAR(36),
    APP_JSON TEXT,
    UNIQUE (APP_ID, DEPLOYMENT_ID),
    FOREIGN KEY (BRANDING_ID, DEPLOYMENT_ID) REFERENCES BRANDING(BRANDING_ID, DEPLOYMENT_ID) ON DELETE RESTRICT
);

-- Index for deployment isolation on SP_APP
CREATE INDEX idx_sp_app_deployment_id ON SP_APP (DEPLOYMENT_ID);

-- Index for efficient lookups of applications by branding.
CREATE INDEX idx_sp_app_branding_id ON SP_APP(BRANDING_ID);

-- Table to store OAuth configurations for SP apps.
CREATE TABLE IDN_OAUTH_CONSUMER_APPS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    CONSUMER_KEY VARCHAR(255) NOT NULL,
    CONSUMER_SECRET VARCHAR(255) NOT NULL,
    APP_ID VARCHAR(36) NOT NULL,
    OAUTH_CONFIG_JSON TEXT,
    FOREIGN KEY (APP_ID, DEPLOYMENT_ID) REFERENCES SP_APP(APP_ID, DEPLOYMENT_ID) ON DELETE CASCADE
);

-- Index for deployment isolation on IDN_OAUTH_CONSUMER_APPS
CREATE INDEX idx_idn_oauth_consumer_apps_deployment_id ON IDN_OAUTH_CONSUMER_APPS (DEPLOYMENT_ID);

-- Table to store inbound auth configs (e.g., OAuth, SAML) for SP apps.
CREATE TABLE SP_INBOUND_AUTH (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    INBOUND_AUTH_KEY VARCHAR(255) NOT NULL,
    INBOUND_AUTH_TYPE VARCHAR(50) NOT NULL,
    APP_ID VARCHAR(36) NOT NULL,
    FOREIGN KEY (APP_ID, DEPLOYMENT_ID) REFERENCES SP_APP(APP_ID, DEPLOYMENT_ID) ON DELETE CASCADE
);

-- Index for deployment isolation on SP_INBOUND_AUTH
CREATE INDEX idx_sp_inbound_auth_deployment_id ON SP_INBOUND_AUTH (DEPLOYMENT_ID);

-- Table to store identity providers.
CREATE TABLE IDP (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    IDP_ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(500),
    TYPE VARCHAR(20) NOT NULL,
    PROPERTIES TEXT,
    CREATED_AT TEXT DEFAULT (datetime('now')),
    UPDATED_AT TEXT DEFAULT (datetime('now')),
    UNIQUE (IDP_ID, DEPLOYMENT_ID)
);

-- Index for deployment isolation on IDP
CREATE INDEX idx_idp_deployment_id ON IDP (DEPLOYMENT_ID);

-- Table to store notification senders.
CREATE TABLE NOTIFICATION_SENDER (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    SENDER_ID VARCHAR(36) NOT NULL,
    DESCRIPTION VARCHAR(500),
    TYPE VARCHAR(20) NOT NULL,
    PROVIDER VARCHAR(20) NOT NULL,
    PROPERTIES TEXT,
    CREATED_AT TEXT DEFAULT (datetime('now')),
    UPDATED_AT TEXT DEFAULT (datetime('now')),
    UNIQUE (SENDER_ID, DEPLOYMENT_ID)
);

-- Index for deployment isolation on NOTIFICATION_SENDER
CREATE INDEX idx_notification_sender_deployment_id ON NOTIFICATION_SENDER (DEPLOYMENT_ID);

-- Table to store certificates associated with various entities.
CREATE TABLE CERTIFICATE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    CERT_ID VARCHAR(36) NOT NULL,
    REF_TYPE VARCHAR(20) NOT NULL,
    REF_ID VARCHAR(36) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    VALUE TEXT NOT NULL,
    CREATED_AT TEXT DEFAULT (datetime('now')),
    UPDATED_AT TEXT DEFAULT (datetime('now')),
    UNIQUE (CERT_ID, DEPLOYMENT_ID),
    UNIQUE (REF_TYPE, REF_ID, DEPLOYMENT_ID)
);

-- Index for deployment isolation on CERTIFICATE
CREATE INDEX idx_certificate_deployment_id ON CERTIFICATE (DEPLOYMENT_ID);
