-- Table to store Organization Units
CREATE TABLE ORGANIZATION_UNIT (
    ID              INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    OU_ID           VARCHAR(36) UNIQUE NOT NULL,
    PARENT_ID       VARCHAR(36),
    HANDLE          VARCHAR(100)        NOT NULL,
    NAME            VARCHAR(100)        NOT NULL,
    DESCRIPTION     VARCHAR(255),
    CREATED_AT      TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT      TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (PARENT_ID) REFERENCES ORGANIZATION_UNIT (OU_ID) ON DELETE CASCADE
);

-- Table to store Users
CREATE TABLE "USER" (
    ID          INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID     VARCHAR(36) UNIQUE NOT NULL,
    OU_ID       VARCHAR(36)        NOT NULL,
    TYPE        VARCHAR(50)        NOT NULL,
    ATTRIBUTES  JSONB,
    CREDENTIALS JSONB,
    CREATED_AT  TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT  TIMESTAMPTZ DEFAULT NOW()
);

-- Table to store Groups
CREATE TABLE "GROUP" (
    ID              INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    GROUP_ID        VARCHAR(36) UNIQUE NOT NULL,
    OU_ID           VARCHAR(36)        NOT NULL,
    NAME            VARCHAR(50)        NOT NULL,
    DESCRIPTION     VARCHAR(255),
    CREATED_AT      TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT      TIMESTAMPTZ DEFAULT NOW()
);

-- Table to store Group member assignments
CREATE TABLE GROUP_MEMBER_REFERENCE (
    ID          INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    GROUP_ID    VARCHAR(36) NOT NULL,
    MEMBER_TYPE VARCHAR(7)  NOT NULL,
    MEMBER_ID   VARCHAR(36) NOT NULL,
    CREATED_AT  TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT  TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (GROUP_ID) REFERENCES "GROUP" (GROUP_ID) ON DELETE CASCADE
);
