// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dcr

import (
	"github.com/asgardeo/thunder/internal/system/error/serviceerror"
	mock "github.com/stretchr/testify/mock"
)

// NewDCRServiceInterfaceMock creates a new instance of DCRServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDCRServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DCRServiceInterfaceMock {
	mock := &DCRServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DCRServiceInterfaceMock is an autogenerated mock type for the DCRServiceInterface type
type DCRServiceInterfaceMock struct {
	mock.Mock
}

type DCRServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *DCRServiceInterfaceMock) EXPECT() *DCRServiceInterfaceMock_Expecter {
	return &DCRServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// RegisterClient provides a mock function for the type DCRServiceInterfaceMock
func (_mock *DCRServiceInterfaceMock) RegisterClient(request *DCRRegistrationRequest) (*DCRRegistrationResponse, *serviceerror.ServiceError) {
	ret := _mock.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for RegisterClient")
	}

	var r0 *DCRRegistrationResponse
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(*DCRRegistrationRequest) (*DCRRegistrationResponse, *serviceerror.ServiceError)); ok {
		return returnFunc(request)
	}
	if returnFunc, ok := ret.Get(0).(func(*DCRRegistrationRequest) *DCRRegistrationResponse); ok {
		r0 = returnFunc(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DCRRegistrationResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*DCRRegistrationRequest) *serviceerror.ServiceError); ok {
		r1 = returnFunc(request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// DCRServiceInterfaceMock_RegisterClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterClient'
type DCRServiceInterfaceMock_RegisterClient_Call struct {
	*mock.Call
}

// RegisterClient is a helper method to define mock.On call
//   - request *DCRRegistrationRequest
func (_e *DCRServiceInterfaceMock_Expecter) RegisterClient(request interface{}) *DCRServiceInterfaceMock_RegisterClient_Call {
	return &DCRServiceInterfaceMock_RegisterClient_Call{Call: _e.mock.On("RegisterClient", request)}
}

func (_c *DCRServiceInterfaceMock_RegisterClient_Call) Run(run func(request *DCRRegistrationRequest)) *DCRServiceInterfaceMock_RegisterClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *DCRRegistrationRequest
		if args[0] != nil {
			arg0 = args[0].(*DCRRegistrationRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DCRServiceInterfaceMock_RegisterClient_Call) Return(dCRRegistrationResponse *DCRRegistrationResponse, serviceError *serviceerror.ServiceError) *DCRServiceInterfaceMock_RegisterClient_Call {
	_c.Call.Return(dCRRegistrationResponse, serviceError)
	return _c
}

func (_c *DCRServiceInterfaceMock_RegisterClient_Call) RunAndReturn(run func(request *DCRRegistrationRequest) (*DCRRegistrationResponse, *serviceerror.ServiceError)) *DCRServiceInterfaceMock_RegisterClient_Call {
	_c.Call.Return(run)
	return _c
}
