/**
 * Copyright (c) 2025, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import type {InboundAuthConfig} from './inbound-auth';

/**
 * Application Response Model (Basic)
 *
 * Basic application information returned in list operations.
 * Contains high-level metadata without detailed configuration.
 *
 * @public
 * @remarks
 * This model is typically returned by GET /applications (list endpoint).
 * For full details including OAuth2 configuration, fetch a specific application by ID.
 *
 * Note: The `client_id` field is included here but doesn't exist in the full `Application` type.
 * It represents the OAuth2 client identifier generated by the server.
 *
 * @example
 * ```typescript
 * // Example response from GET /applications
 * const appList: BasicApplication[] = [
 *   {
 *     id: '550e8400-e29b-41d4-a716-446655440000',
 *     name: 'My Web Application',
 *     description: 'Customer portal application',
 *     client_id: 'myapp_client_id',
 *     logo_url: 'https://myapp.com/logo.png',
 *     auth_flow_graph_id: 'auth_flow_config_basic',
 *     registration_flow_graph_id: 'registration_flow_config_basic',
 *     is_registration_flow_enabled: true
 *   }
 * ];
 * ```
 */
export type BasicApplication = Pick<
  Application,
  | 'id'
  | 'name'
  | 'description'
  | 'logo_url'
  | 'auth_flow_graph_id'
  | 'registration_flow_graph_id'
  | 'is_registration_flow_enabled'
> & {
  /**
   * OAuth2 client identifier
   * Generated by the server for OAuth2/OIDC applications
   * @example 'myapp_client_id'
   */
  client_id?: string;
};

/**
 * Application Response Model (Full)
 *
 * Complete application information including all configuration details.
 * This is the full representation returned when fetching a specific application.
 *
 * @public
 * @remarks
 * This model is returned by:
 * - GET /applications/:id (get by ID)
 * - POST /applications (create)
 * - PUT /applications/:id (update)
 *
 * The response includes:
 * - All basic metadata (name, description, URLs)
 * - Generated identifiers (id, client_id)
 * - Complete OAuth2/OIDC configuration
 * - Timestamps (created_at, updated_at)
 *
 * Note: The client_secret is only returned during creation and is masked in subsequent GET requests.
 *
 * @example
 * ```typescript
 * // Example response from GET /applications/:id
 * const app: Application = {
 *   id: '550e8400-e29b-41d4-a716-446655440000',
 *   name: 'My Web Application',
 *   description: 'Customer portal application',
 *   url: 'https://myapp.com',
 *   logo_url: 'https://myapp.com/logo.png',
 *   tos_uri: 'https://myapp.com/terms',
 *   policy_uri: 'https://myapp.com/privacy',
 *   contacts: ['admin@myapp.com'],
 *   auth_flow_graph_id: 'auth_flow_config_basic',
 *   registration_flow_graph_id: 'registration_flow_config_basic',
 *   is_registration_flow_enabled: true,
 *   user_attributes: ['email', 'username'],
 *   inbound_auth_config: [{
 *     type: 'oauth2',
 *     config: {
 *       client_id: 'myapp_client_id',
 *       client_secret: '******', // Masked in GET responses
 *       redirect_uris: ['https://myapp.com/callback'],
 *       grant_types: ['authorization_code', 'refresh_token'],
 *       response_types: ['code'],
 *       scopes: ['openid', 'profile', 'email'],
 *       token: {
 *         issuer: 'thunder',
 *         access_token: {
 *           validity_period: 3600,
 *           user_attributes: ['email', 'username']
 *         },
 *         id_token: {
 *           validity_period: 3600,
 *           user_attributes: ['sub', 'email', 'name'],
 *           scope_claims: {
 *             profile: ['name', 'picture'],
 *             email: ['email', 'email_verified']
 *           }
 *         }
 *       }
 *     }
 *   }],
 *   created_at: '2025-01-15T10:30:00Z',
 *   updated_at: '2025-01-15T10:30:00Z'
 * };
 * ```
 */
export interface Application {
  /**
   * Unique identifier of the application
   * Generated by the server upon creation
   * @example '550e8400-e29b-41d4-a716-446655440000'
   */
  id: string;

  /**
   * Application name
   * @example 'My Web Application'
   */
  name: string;

  /**
   * Application description
   * @example 'Customer portal application'
   */
  description?: string;

  /**
   * Application URL
   * @example 'https://myapp.example.com'
   */
  url?: string;

  /**
   * Application logo URL
   * @example 'https://myapp.example.com/logo.png'
   */
  logo_url?: string;

  /**
   * Terms of Service URI
   * @example 'https://myapp.example.com/terms'
   */
  tos_uri?: string;

  /**
   * Privacy Policy URI
   * @example 'https://myapp.example.com/privacy'
   */
  policy_uri?: string;

  /**
   * Contact email addresses
   * @example ['admin@myapp.example.com', 'support@myapp.example.com']
   */
  contacts?: string[];

  /**
   * Authentication flow graph ID
   * @example 'auth_flow_config_basic'
   */
  auth_flow_graph_id?: string;

  /**
   * Registration flow graph ID
   * @example 'registration_flow_config_basic'
   */
  registration_flow_graph_id?: string;

  /**
   * Whether registration flow is enabled
   * @example true
   */
  is_registration_flow_enabled?: boolean;

  /**
   * User attributes to include
   * @example ['email', 'username', 'given_name', 'family_name', 'roles']
   */
  user_attributes?: string[];

  /**
   * Allowed user types (user schema IDs) that can access this application
   * @example ['person', 'person_2', 'person_3']
   */
  allowed_user_types?: string[];

  /**
   * Inbound authentication configuration
   * Contains OAuth2/OIDC settings
   * Note: client_secret is masked in GET responses
   * @see InboundAuthConfig
   */
  inbound_auth_config?: InboundAuthConfig[];

  /**
   * Timestamp when the application was created
   * ISO 8601 format
   * @example '2025-01-15T10:30:00Z'
   */
  created_at?: string;

  /**
   * Timestamp when the application was last updated
   * ISO 8601 format
   * @example '2025-01-15T14:45:00Z'
   */
  updated_at?: string;

  /**
   * Additional dynamic properties
   * Allows for extension fields not explicitly defined in the interface
   */
  [key: string]: unknown;
}
