// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package brandingmock

import (
	"github.com/asgardeo/thunder/internal/branding"
	mock "github.com/stretchr/testify/mock"
)

// newBrandingStoreInterfaceMock creates a new instance of brandingStoreInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newBrandingStoreInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *brandingStoreInterfaceMock {
	mock := &brandingStoreInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// brandingStoreInterfaceMock is an autogenerated mock type for the brandingStoreInterface type
type brandingStoreInterfaceMock struct {
	mock.Mock
}

type brandingStoreInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *brandingStoreInterfaceMock) EXPECT() *brandingStoreInterfaceMock_Expecter {
	return &brandingStoreInterfaceMock_Expecter{mock: &_m.Mock}
}

// CreateBranding provides a mock function for the type brandingStoreInterfaceMock
func (_mock *brandingStoreInterfaceMock) CreateBranding(id string, branding1 branding.CreateBrandingRequest) error {
	ret := _mock.Called(id, branding1)

	if len(ret) == 0 {
		panic("no return value specified for CreateBranding")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, branding.CreateBrandingRequest) error); ok {
		r0 = returnFunc(id, branding1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// brandingStoreInterfaceMock_CreateBranding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBranding'
type brandingStoreInterfaceMock_CreateBranding_Call struct {
	*mock.Call
}

// CreateBranding is a helper method to define mock.On call
//   - id string
//   - branding1 branding.CreateBrandingRequest
func (_e *brandingStoreInterfaceMock_Expecter) CreateBranding(id interface{}, branding1 interface{}) *brandingStoreInterfaceMock_CreateBranding_Call {
	return &brandingStoreInterfaceMock_CreateBranding_Call{Call: _e.mock.On("CreateBranding", id, branding1)}
}

func (_c *brandingStoreInterfaceMock_CreateBranding_Call) Run(run func(id string, branding1 branding.CreateBrandingRequest)) *brandingStoreInterfaceMock_CreateBranding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 branding.CreateBrandingRequest
		if args[1] != nil {
			arg1 = args[1].(branding.CreateBrandingRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *brandingStoreInterfaceMock_CreateBranding_Call) Return(err error) *brandingStoreInterfaceMock_CreateBranding_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *brandingStoreInterfaceMock_CreateBranding_Call) RunAndReturn(run func(id string, branding1 branding.CreateBrandingRequest) error) *brandingStoreInterfaceMock_CreateBranding_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBranding provides a mock function for the type brandingStoreInterfaceMock
func (_mock *brandingStoreInterfaceMock) DeleteBranding(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBranding")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// brandingStoreInterfaceMock_DeleteBranding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBranding'
type brandingStoreInterfaceMock_DeleteBranding_Call struct {
	*mock.Call
}

// DeleteBranding is a helper method to define mock.On call
//   - id string
func (_e *brandingStoreInterfaceMock_Expecter) DeleteBranding(id interface{}) *brandingStoreInterfaceMock_DeleteBranding_Call {
	return &brandingStoreInterfaceMock_DeleteBranding_Call{Call: _e.mock.On("DeleteBranding", id)}
}

func (_c *brandingStoreInterfaceMock_DeleteBranding_Call) Run(run func(id string)) *brandingStoreInterfaceMock_DeleteBranding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *brandingStoreInterfaceMock_DeleteBranding_Call) Return(err error) *brandingStoreInterfaceMock_DeleteBranding_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *brandingStoreInterfaceMock_DeleteBranding_Call) RunAndReturn(run func(id string) error) *brandingStoreInterfaceMock_DeleteBranding_Call {
	_c.Call.Return(run)
	return _c
}

// GetApplicationsCountByBrandingID provides a mock function for the type brandingStoreInterfaceMock
func (_mock *brandingStoreInterfaceMock) GetApplicationsCountByBrandingID(id string) (int, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetApplicationsCountByBrandingID")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (int, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// brandingStoreInterfaceMock_GetApplicationsCountByBrandingID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApplicationsCountByBrandingID'
type brandingStoreInterfaceMock_GetApplicationsCountByBrandingID_Call struct {
	*mock.Call
}

// GetApplicationsCountByBrandingID is a helper method to define mock.On call
//   - id string
func (_e *brandingStoreInterfaceMock_Expecter) GetApplicationsCountByBrandingID(id interface{}) *brandingStoreInterfaceMock_GetApplicationsCountByBrandingID_Call {
	return &brandingStoreInterfaceMock_GetApplicationsCountByBrandingID_Call{Call: _e.mock.On("GetApplicationsCountByBrandingID", id)}
}

func (_c *brandingStoreInterfaceMock_GetApplicationsCountByBrandingID_Call) Run(run func(id string)) *brandingStoreInterfaceMock_GetApplicationsCountByBrandingID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *brandingStoreInterfaceMock_GetApplicationsCountByBrandingID_Call) Return(n int, err error) *brandingStoreInterfaceMock_GetApplicationsCountByBrandingID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *brandingStoreInterfaceMock_GetApplicationsCountByBrandingID_Call) RunAndReturn(run func(id string) (int, error)) *brandingStoreInterfaceMock_GetApplicationsCountByBrandingID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBranding provides a mock function for the type brandingStoreInterfaceMock
func (_mock *brandingStoreInterfaceMock) GetBranding(id string) (branding.Branding, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetBranding")
	}

	var r0 branding.Branding
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (branding.Branding, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) branding.Branding); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(branding.Branding)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// brandingStoreInterfaceMock_GetBranding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBranding'
type brandingStoreInterfaceMock_GetBranding_Call struct {
	*mock.Call
}

// GetBranding is a helper method to define mock.On call
//   - id string
func (_e *brandingStoreInterfaceMock_Expecter) GetBranding(id interface{}) *brandingStoreInterfaceMock_GetBranding_Call {
	return &brandingStoreInterfaceMock_GetBranding_Call{Call: _e.mock.On("GetBranding", id)}
}

func (_c *brandingStoreInterfaceMock_GetBranding_Call) Run(run func(id string)) *brandingStoreInterfaceMock_GetBranding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *brandingStoreInterfaceMock_GetBranding_Call) Return(branding1 branding.Branding, err error) *brandingStoreInterfaceMock_GetBranding_Call {
	_c.Call.Return(branding1, err)
	return _c
}

func (_c *brandingStoreInterfaceMock_GetBranding_Call) RunAndReturn(run func(id string) (branding.Branding, error)) *brandingStoreInterfaceMock_GetBranding_Call {
	_c.Call.Return(run)
	return _c
}

// GetBrandingList provides a mock function for the type brandingStoreInterfaceMock
func (_mock *brandingStoreInterfaceMock) GetBrandingList(limit int, offset int) ([]branding.Branding, error) {
	ret := _mock.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetBrandingList")
	}

	var r0 []branding.Branding
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int) ([]branding.Branding, error)); ok {
		return returnFunc(limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) []branding.Branding); ok {
		r0 = returnFunc(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]branding.Branding)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = returnFunc(limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// brandingStoreInterfaceMock_GetBrandingList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBrandingList'
type brandingStoreInterfaceMock_GetBrandingList_Call struct {
	*mock.Call
}

// GetBrandingList is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *brandingStoreInterfaceMock_Expecter) GetBrandingList(limit interface{}, offset interface{}) *brandingStoreInterfaceMock_GetBrandingList_Call {
	return &brandingStoreInterfaceMock_GetBrandingList_Call{Call: _e.mock.On("GetBrandingList", limit, offset)}
}

func (_c *brandingStoreInterfaceMock_GetBrandingList_Call) Run(run func(limit int, offset int)) *brandingStoreInterfaceMock_GetBrandingList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *brandingStoreInterfaceMock_GetBrandingList_Call) Return(brandings []branding.Branding, err error) *brandingStoreInterfaceMock_GetBrandingList_Call {
	_c.Call.Return(brandings, err)
	return _c
}

func (_c *brandingStoreInterfaceMock_GetBrandingList_Call) RunAndReturn(run func(limit int, offset int) ([]branding.Branding, error)) *brandingStoreInterfaceMock_GetBrandingList_Call {
	_c.Call.Return(run)
	return _c
}

// GetBrandingListCount provides a mock function for the type brandingStoreInterfaceMock
func (_mock *brandingStoreInterfaceMock) GetBrandingListCount() (int, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBrandingListCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// brandingStoreInterfaceMock_GetBrandingListCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBrandingListCount'
type brandingStoreInterfaceMock_GetBrandingListCount_Call struct {
	*mock.Call
}

// GetBrandingListCount is a helper method to define mock.On call
func (_e *brandingStoreInterfaceMock_Expecter) GetBrandingListCount() *brandingStoreInterfaceMock_GetBrandingListCount_Call {
	return &brandingStoreInterfaceMock_GetBrandingListCount_Call{Call: _e.mock.On("GetBrandingListCount")}
}

func (_c *brandingStoreInterfaceMock_GetBrandingListCount_Call) Run(run func()) *brandingStoreInterfaceMock_GetBrandingListCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *brandingStoreInterfaceMock_GetBrandingListCount_Call) Return(n int, err error) *brandingStoreInterfaceMock_GetBrandingListCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *brandingStoreInterfaceMock_GetBrandingListCount_Call) RunAndReturn(run func() (int, error)) *brandingStoreInterfaceMock_GetBrandingListCount_Call {
	_c.Call.Return(run)
	return _c
}

// IsBrandingExist provides a mock function for the type brandingStoreInterfaceMock
func (_mock *brandingStoreInterfaceMock) IsBrandingExist(id string) (bool, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for IsBrandingExist")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// brandingStoreInterfaceMock_IsBrandingExist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsBrandingExist'
type brandingStoreInterfaceMock_IsBrandingExist_Call struct {
	*mock.Call
}

// IsBrandingExist is a helper method to define mock.On call
//   - id string
func (_e *brandingStoreInterfaceMock_Expecter) IsBrandingExist(id interface{}) *brandingStoreInterfaceMock_IsBrandingExist_Call {
	return &brandingStoreInterfaceMock_IsBrandingExist_Call{Call: _e.mock.On("IsBrandingExist", id)}
}

func (_c *brandingStoreInterfaceMock_IsBrandingExist_Call) Run(run func(id string)) *brandingStoreInterfaceMock_IsBrandingExist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *brandingStoreInterfaceMock_IsBrandingExist_Call) Return(b bool, err error) *brandingStoreInterfaceMock_IsBrandingExist_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *brandingStoreInterfaceMock_IsBrandingExist_Call) RunAndReturn(run func(id string) (bool, error)) *brandingStoreInterfaceMock_IsBrandingExist_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBranding provides a mock function for the type brandingStoreInterfaceMock
func (_mock *brandingStoreInterfaceMock) UpdateBranding(id string, branding1 branding.UpdateBrandingRequest) error {
	ret := _mock.Called(id, branding1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBranding")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, branding.UpdateBrandingRequest) error); ok {
		r0 = returnFunc(id, branding1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// brandingStoreInterfaceMock_UpdateBranding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBranding'
type brandingStoreInterfaceMock_UpdateBranding_Call struct {
	*mock.Call
}

// UpdateBranding is a helper method to define mock.On call
//   - id string
//   - branding1 branding.UpdateBrandingRequest
func (_e *brandingStoreInterfaceMock_Expecter) UpdateBranding(id interface{}, branding1 interface{}) *brandingStoreInterfaceMock_UpdateBranding_Call {
	return &brandingStoreInterfaceMock_UpdateBranding_Call{Call: _e.mock.On("UpdateBranding", id, branding1)}
}

func (_c *brandingStoreInterfaceMock_UpdateBranding_Call) Run(run func(id string, branding1 branding.UpdateBrandingRequest)) *brandingStoreInterfaceMock_UpdateBranding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 branding.UpdateBrandingRequest
		if args[1] != nil {
			arg1 = args[1].(branding.UpdateBrandingRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *brandingStoreInterfaceMock_UpdateBranding_Call) Return(err error) *brandingStoreInterfaceMock_UpdateBranding_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *brandingStoreInterfaceMock_UpdateBranding_Call) RunAndReturn(run func(id string, branding1 branding.UpdateBrandingRequest) error) *brandingStoreInterfaceMock_UpdateBranding_Call {
	_c.Call.Return(run)
	return _c
}
