// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package flowexec

import (
	mock "github.com/stretchr/testify/mock"
)

// newFlowStoreInterfaceMock creates a new instance of flowStoreInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newFlowStoreInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *flowStoreInterfaceMock {
	mock := &flowStoreInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// flowStoreInterfaceMock is an autogenerated mock type for the flowStoreInterface type
type flowStoreInterfaceMock struct {
	mock.Mock
}

type flowStoreInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *flowStoreInterfaceMock) EXPECT() *flowStoreInterfaceMock_Expecter {
	return &flowStoreInterfaceMock_Expecter{mock: &_m.Mock}
}

// DeleteFlowContext provides a mock function for the type flowStoreInterfaceMock
func (_mock *flowStoreInterfaceMock) DeleteFlowContext(flowID string) error {
	ret := _mock.Called(flowID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFlowContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(flowID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// flowStoreInterfaceMock_DeleteFlowContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFlowContext'
type flowStoreInterfaceMock_DeleteFlowContext_Call struct {
	*mock.Call
}

// DeleteFlowContext is a helper method to define mock.On call
//   - flowID string
func (_e *flowStoreInterfaceMock_Expecter) DeleteFlowContext(flowID interface{}) *flowStoreInterfaceMock_DeleteFlowContext_Call {
	return &flowStoreInterfaceMock_DeleteFlowContext_Call{Call: _e.mock.On("DeleteFlowContext", flowID)}
}

func (_c *flowStoreInterfaceMock_DeleteFlowContext_Call) Run(run func(flowID string)) *flowStoreInterfaceMock_DeleteFlowContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *flowStoreInterfaceMock_DeleteFlowContext_Call) Return(err error) *flowStoreInterfaceMock_DeleteFlowContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *flowStoreInterfaceMock_DeleteFlowContext_Call) RunAndReturn(run func(flowID string) error) *flowStoreInterfaceMock_DeleteFlowContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetFlowContext provides a mock function for the type flowStoreInterfaceMock
func (_mock *flowStoreInterfaceMock) GetFlowContext(flowID string) (*FlowContextWithUserDataDB, error) {
	ret := _mock.Called(flowID)

	if len(ret) == 0 {
		panic("no return value specified for GetFlowContext")
	}

	var r0 *FlowContextWithUserDataDB
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*FlowContextWithUserDataDB, error)); ok {
		return returnFunc(flowID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *FlowContextWithUserDataDB); ok {
		r0 = returnFunc(flowID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*FlowContextWithUserDataDB)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(flowID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// flowStoreInterfaceMock_GetFlowContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlowContext'
type flowStoreInterfaceMock_GetFlowContext_Call struct {
	*mock.Call
}

// GetFlowContext is a helper method to define mock.On call
//   - flowID string
func (_e *flowStoreInterfaceMock_Expecter) GetFlowContext(flowID interface{}) *flowStoreInterfaceMock_GetFlowContext_Call {
	return &flowStoreInterfaceMock_GetFlowContext_Call{Call: _e.mock.On("GetFlowContext", flowID)}
}

func (_c *flowStoreInterfaceMock_GetFlowContext_Call) Run(run func(flowID string)) *flowStoreInterfaceMock_GetFlowContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *flowStoreInterfaceMock_GetFlowContext_Call) Return(flowContextWithUserDataDB *FlowContextWithUserDataDB, err error) *flowStoreInterfaceMock_GetFlowContext_Call {
	_c.Call.Return(flowContextWithUserDataDB, err)
	return _c
}

func (_c *flowStoreInterfaceMock_GetFlowContext_Call) RunAndReturn(run func(flowID string) (*FlowContextWithUserDataDB, error)) *flowStoreInterfaceMock_GetFlowContext_Call {
	_c.Call.Return(run)
	return _c
}

// StoreFlowContext provides a mock function for the type flowStoreInterfaceMock
func (_mock *flowStoreInterfaceMock) StoreFlowContext(ctx EngineContext) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StoreFlowContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(EngineContext) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// flowStoreInterfaceMock_StoreFlowContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreFlowContext'
type flowStoreInterfaceMock_StoreFlowContext_Call struct {
	*mock.Call
}

// StoreFlowContext is a helper method to define mock.On call
//   - ctx EngineContext
func (_e *flowStoreInterfaceMock_Expecter) StoreFlowContext(ctx interface{}) *flowStoreInterfaceMock_StoreFlowContext_Call {
	return &flowStoreInterfaceMock_StoreFlowContext_Call{Call: _e.mock.On("StoreFlowContext", ctx)}
}

func (_c *flowStoreInterfaceMock_StoreFlowContext_Call) Run(run func(ctx EngineContext)) *flowStoreInterfaceMock_StoreFlowContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 EngineContext
		if args[0] != nil {
			arg0 = args[0].(EngineContext)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *flowStoreInterfaceMock_StoreFlowContext_Call) Return(err error) *flowStoreInterfaceMock_StoreFlowContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *flowStoreInterfaceMock_StoreFlowContext_Call) RunAndReturn(run func(ctx EngineContext) error) *flowStoreInterfaceMock_StoreFlowContext_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFlowContext provides a mock function for the type flowStoreInterfaceMock
func (_mock *flowStoreInterfaceMock) UpdateFlowContext(ctx EngineContext) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFlowContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(EngineContext) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// flowStoreInterfaceMock_UpdateFlowContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFlowContext'
type flowStoreInterfaceMock_UpdateFlowContext_Call struct {
	*mock.Call
}

// UpdateFlowContext is a helper method to define mock.On call
//   - ctx EngineContext
func (_e *flowStoreInterfaceMock_Expecter) UpdateFlowContext(ctx interface{}) *flowStoreInterfaceMock_UpdateFlowContext_Call {
	return &flowStoreInterfaceMock_UpdateFlowContext_Call{Call: _e.mock.On("UpdateFlowContext", ctx)}
}

func (_c *flowStoreInterfaceMock_UpdateFlowContext_Call) Run(run func(ctx EngineContext)) *flowStoreInterfaceMock_UpdateFlowContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 EngineContext
		if args[0] != nil {
			arg0 = args[0].(EngineContext)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *flowStoreInterfaceMock_UpdateFlowContext_Call) Return(err error) *flowStoreInterfaceMock_UpdateFlowContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *flowStoreInterfaceMock_UpdateFlowContext_Call) RunAndReturn(run func(ctx EngineContext) error) *flowStoreInterfaceMock_UpdateFlowContext_Call {
	_c.Call.Return(run)
	return _c
}
