// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package notificationmock

import (
	"github.com/asgardeo/thunder/internal/notification/common"
	"github.com/asgardeo/thunder/internal/notification/message"
	"github.com/asgardeo/thunder/internal/system/error/serviceerror"
	mock "github.com/stretchr/testify/mock"
)

// newNotificationClientProviderInterfaceMock creates a new instance of notificationClientProviderInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newNotificationClientProviderInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *notificationClientProviderInterfaceMock {
	mock := &notificationClientProviderInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// notificationClientProviderInterfaceMock is an autogenerated mock type for the notificationClientProviderInterface type
type notificationClientProviderInterfaceMock struct {
	mock.Mock
}

type notificationClientProviderInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *notificationClientProviderInterfaceMock) EXPECT() *notificationClientProviderInterfaceMock_Expecter {
	return &notificationClientProviderInterfaceMock_Expecter{mock: &_m.Mock}
}

// GetMessageClient provides a mock function for the type notificationClientProviderInterfaceMock
func (_mock *notificationClientProviderInterfaceMock) GetMessageClient(sender common.NotificationSenderDTO) (message.MessageClientInterface, *serviceerror.ServiceError) {
	ret := _mock.Called(sender)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageClient")
	}

	var r0 message.MessageClientInterface
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(common.NotificationSenderDTO) (message.MessageClientInterface, *serviceerror.ServiceError)); ok {
		return returnFunc(sender)
	}
	if returnFunc, ok := ret.Get(0).(func(common.NotificationSenderDTO) message.MessageClientInterface); ok {
		r0 = returnFunc(sender)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(message.MessageClientInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(common.NotificationSenderDTO) *serviceerror.ServiceError); ok {
		r1 = returnFunc(sender)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// notificationClientProviderInterfaceMock_GetMessageClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessageClient'
type notificationClientProviderInterfaceMock_GetMessageClient_Call struct {
	*mock.Call
}

// GetMessageClient is a helper method to define mock.On call
//   - sender common.NotificationSenderDTO
func (_e *notificationClientProviderInterfaceMock_Expecter) GetMessageClient(sender interface{}) *notificationClientProviderInterfaceMock_GetMessageClient_Call {
	return &notificationClientProviderInterfaceMock_GetMessageClient_Call{Call: _e.mock.On("GetMessageClient", sender)}
}

func (_c *notificationClientProviderInterfaceMock_GetMessageClient_Call) Run(run func(sender common.NotificationSenderDTO)) *notificationClientProviderInterfaceMock_GetMessageClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 common.NotificationSenderDTO
		if args[0] != nil {
			arg0 = args[0].(common.NotificationSenderDTO)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *notificationClientProviderInterfaceMock_GetMessageClient_Call) Return(messageClientInterface message.MessageClientInterface, serviceError *serviceerror.ServiceError) *notificationClientProviderInterfaceMock_GetMessageClient_Call {
	_c.Call.Return(messageClientInterface, serviceError)
	return _c
}

func (_c *notificationClientProviderInterfaceMock_GetMessageClient_Call) RunAndReturn(run func(sender common.NotificationSenderDTO) (message.MessageClientInterface, *serviceerror.ServiceError)) *notificationClientProviderInterfaceMock_GetMessageClient_Call {
	_c.Call.Return(run)
	return _c
}
