// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"github.com/asgardeo/thunder/internal/flow/common"
	"github.com/asgardeo/thunder/internal/system/error/serviceerror"
	mock "github.com/stretchr/testify/mock"
)

// NewExecutorBackedNodeInterfaceMock creates a new instance of ExecutorBackedNodeInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExecutorBackedNodeInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExecutorBackedNodeInterfaceMock {
	mock := &ExecutorBackedNodeInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ExecutorBackedNodeInterfaceMock is an autogenerated mock type for the ExecutorBackedNodeInterface type
type ExecutorBackedNodeInterfaceMock struct {
	mock.Mock
}

type ExecutorBackedNodeInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ExecutorBackedNodeInterfaceMock) EXPECT() *ExecutorBackedNodeInterfaceMock_Expecter {
	return &ExecutorBackedNodeInterfaceMock_Expecter{mock: &_m.Mock}
}

// AddNextNodeID provides a mock function for the type ExecutorBackedNodeInterfaceMock
func (_mock *ExecutorBackedNodeInterfaceMock) AddNextNodeID(nextNodeID string) {
	_mock.Called(nextNodeID)
	return
}

// ExecutorBackedNodeInterfaceMock_AddNextNodeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddNextNodeID'
type ExecutorBackedNodeInterfaceMock_AddNextNodeID_Call struct {
	*mock.Call
}

// AddNextNodeID is a helper method to define mock.On call
//   - nextNodeID string
func (_e *ExecutorBackedNodeInterfaceMock_Expecter) AddNextNodeID(nextNodeID interface{}) *ExecutorBackedNodeInterfaceMock_AddNextNodeID_Call {
	return &ExecutorBackedNodeInterfaceMock_AddNextNodeID_Call{Call: _e.mock.On("AddNextNodeID", nextNodeID)}
}

func (_c *ExecutorBackedNodeInterfaceMock_AddNextNodeID_Call) Run(run func(nextNodeID string)) *ExecutorBackedNodeInterfaceMock_AddNextNodeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_AddNextNodeID_Call) Return() *ExecutorBackedNodeInterfaceMock_AddNextNodeID_Call {
	_c.Call.Return()
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_AddNextNodeID_Call) RunAndReturn(run func(nextNodeID string)) *ExecutorBackedNodeInterfaceMock_AddNextNodeID_Call {
	_c.Run(run)
	return _c
}

// AddPreviousNodeID provides a mock function for the type ExecutorBackedNodeInterfaceMock
func (_mock *ExecutorBackedNodeInterfaceMock) AddPreviousNodeID(previousNodeID string) {
	_mock.Called(previousNodeID)
	return
}

// ExecutorBackedNodeInterfaceMock_AddPreviousNodeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPreviousNodeID'
type ExecutorBackedNodeInterfaceMock_AddPreviousNodeID_Call struct {
	*mock.Call
}

// AddPreviousNodeID is a helper method to define mock.On call
//   - previousNodeID string
func (_e *ExecutorBackedNodeInterfaceMock_Expecter) AddPreviousNodeID(previousNodeID interface{}) *ExecutorBackedNodeInterfaceMock_AddPreviousNodeID_Call {
	return &ExecutorBackedNodeInterfaceMock_AddPreviousNodeID_Call{Call: _e.mock.On("AddPreviousNodeID", previousNodeID)}
}

func (_c *ExecutorBackedNodeInterfaceMock_AddPreviousNodeID_Call) Run(run func(previousNodeID string)) *ExecutorBackedNodeInterfaceMock_AddPreviousNodeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_AddPreviousNodeID_Call) Return() *ExecutorBackedNodeInterfaceMock_AddPreviousNodeID_Call {
	_c.Call.Return()
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_AddPreviousNodeID_Call) RunAndReturn(run func(previousNodeID string)) *ExecutorBackedNodeInterfaceMock_AddPreviousNodeID_Call {
	_c.Run(run)
	return _c
}

// Execute provides a mock function for the type ExecutorBackedNodeInterfaceMock
func (_mock *ExecutorBackedNodeInterfaceMock) Execute(ctx *NodeContext) (*common.NodeResponse, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *common.NodeResponse
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(*NodeContext) (*common.NodeResponse, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(*NodeContext) *common.NodeResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.NodeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*NodeContext) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// ExecutorBackedNodeInterfaceMock_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ExecutorBackedNodeInterfaceMock_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx *NodeContext
func (_e *ExecutorBackedNodeInterfaceMock_Expecter) Execute(ctx interface{}) *ExecutorBackedNodeInterfaceMock_Execute_Call {
	return &ExecutorBackedNodeInterfaceMock_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *ExecutorBackedNodeInterfaceMock_Execute_Call) Run(run func(ctx *NodeContext)) *ExecutorBackedNodeInterfaceMock_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *NodeContext
		if args[0] != nil {
			arg0 = args[0].(*NodeContext)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_Execute_Call) Return(nodeResponse *common.NodeResponse, serviceError *serviceerror.ServiceError) *ExecutorBackedNodeInterfaceMock_Execute_Call {
	_c.Call.Return(nodeResponse, serviceError)
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_Execute_Call) RunAndReturn(run func(ctx *NodeContext) (*common.NodeResponse, *serviceerror.ServiceError)) *ExecutorBackedNodeInterfaceMock_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// GetExecutor provides a mock function for the type ExecutorBackedNodeInterfaceMock
func (_mock *ExecutorBackedNodeInterfaceMock) GetExecutor() ExecutorInterface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetExecutor")
	}

	var r0 ExecutorInterface
	if returnFunc, ok := ret.Get(0).(func() ExecutorInterface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ExecutorInterface)
		}
	}
	return r0
}

// ExecutorBackedNodeInterfaceMock_GetExecutor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExecutor'
type ExecutorBackedNodeInterfaceMock_GetExecutor_Call struct {
	*mock.Call
}

// GetExecutor is a helper method to define mock.On call
func (_e *ExecutorBackedNodeInterfaceMock_Expecter) GetExecutor() *ExecutorBackedNodeInterfaceMock_GetExecutor_Call {
	return &ExecutorBackedNodeInterfaceMock_GetExecutor_Call{Call: _e.mock.On("GetExecutor")}
}

func (_c *ExecutorBackedNodeInterfaceMock_GetExecutor_Call) Run(run func()) *ExecutorBackedNodeInterfaceMock_GetExecutor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_GetExecutor_Call) Return(executorInterface ExecutorInterface) *ExecutorBackedNodeInterfaceMock_GetExecutor_Call {
	_c.Call.Return(executorInterface)
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_GetExecutor_Call) RunAndReturn(run func() ExecutorInterface) *ExecutorBackedNodeInterfaceMock_GetExecutor_Call {
	_c.Call.Return(run)
	return _c
}

// GetExecutorName provides a mock function for the type ExecutorBackedNodeInterfaceMock
func (_mock *ExecutorBackedNodeInterfaceMock) GetExecutorName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetExecutorName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ExecutorBackedNodeInterfaceMock_GetExecutorName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExecutorName'
type ExecutorBackedNodeInterfaceMock_GetExecutorName_Call struct {
	*mock.Call
}

// GetExecutorName is a helper method to define mock.On call
func (_e *ExecutorBackedNodeInterfaceMock_Expecter) GetExecutorName() *ExecutorBackedNodeInterfaceMock_GetExecutorName_Call {
	return &ExecutorBackedNodeInterfaceMock_GetExecutorName_Call{Call: _e.mock.On("GetExecutorName")}
}

func (_c *ExecutorBackedNodeInterfaceMock_GetExecutorName_Call) Run(run func()) *ExecutorBackedNodeInterfaceMock_GetExecutorName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_GetExecutorName_Call) Return(s string) *ExecutorBackedNodeInterfaceMock_GetExecutorName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_GetExecutorName_Call) RunAndReturn(run func() string) *ExecutorBackedNodeInterfaceMock_GetExecutorName_Call {
	_c.Call.Return(run)
	return _c
}

// GetID provides a mock function for the type ExecutorBackedNodeInterfaceMock
func (_mock *ExecutorBackedNodeInterfaceMock) GetID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ExecutorBackedNodeInterfaceMock_GetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetID'
type ExecutorBackedNodeInterfaceMock_GetID_Call struct {
	*mock.Call
}

// GetID is a helper method to define mock.On call
func (_e *ExecutorBackedNodeInterfaceMock_Expecter) GetID() *ExecutorBackedNodeInterfaceMock_GetID_Call {
	return &ExecutorBackedNodeInterfaceMock_GetID_Call{Call: _e.mock.On("GetID")}
}

func (_c *ExecutorBackedNodeInterfaceMock_GetID_Call) Run(run func()) *ExecutorBackedNodeInterfaceMock_GetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_GetID_Call) Return(s string) *ExecutorBackedNodeInterfaceMock_GetID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_GetID_Call) RunAndReturn(run func() string) *ExecutorBackedNodeInterfaceMock_GetID_Call {
	_c.Call.Return(run)
	return _c
}

// GetInputData provides a mock function for the type ExecutorBackedNodeInterfaceMock
func (_mock *ExecutorBackedNodeInterfaceMock) GetInputData() []common.InputData {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInputData")
	}

	var r0 []common.InputData
	if returnFunc, ok := ret.Get(0).(func() []common.InputData); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.InputData)
		}
	}
	return r0
}

// ExecutorBackedNodeInterfaceMock_GetInputData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInputData'
type ExecutorBackedNodeInterfaceMock_GetInputData_Call struct {
	*mock.Call
}

// GetInputData is a helper method to define mock.On call
func (_e *ExecutorBackedNodeInterfaceMock_Expecter) GetInputData() *ExecutorBackedNodeInterfaceMock_GetInputData_Call {
	return &ExecutorBackedNodeInterfaceMock_GetInputData_Call{Call: _e.mock.On("GetInputData")}
}

func (_c *ExecutorBackedNodeInterfaceMock_GetInputData_Call) Run(run func()) *ExecutorBackedNodeInterfaceMock_GetInputData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_GetInputData_Call) Return(inputDatas []common.InputData) *ExecutorBackedNodeInterfaceMock_GetInputData_Call {
	_c.Call.Return(inputDatas)
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_GetInputData_Call) RunAndReturn(run func() []common.InputData) *ExecutorBackedNodeInterfaceMock_GetInputData_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextNodeList provides a mock function for the type ExecutorBackedNodeInterfaceMock
func (_mock *ExecutorBackedNodeInterfaceMock) GetNextNodeList() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNextNodeList")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// ExecutorBackedNodeInterfaceMock_GetNextNodeList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextNodeList'
type ExecutorBackedNodeInterfaceMock_GetNextNodeList_Call struct {
	*mock.Call
}

// GetNextNodeList is a helper method to define mock.On call
func (_e *ExecutorBackedNodeInterfaceMock_Expecter) GetNextNodeList() *ExecutorBackedNodeInterfaceMock_GetNextNodeList_Call {
	return &ExecutorBackedNodeInterfaceMock_GetNextNodeList_Call{Call: _e.mock.On("GetNextNodeList")}
}

func (_c *ExecutorBackedNodeInterfaceMock_GetNextNodeList_Call) Run(run func()) *ExecutorBackedNodeInterfaceMock_GetNextNodeList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_GetNextNodeList_Call) Return(strings []string) *ExecutorBackedNodeInterfaceMock_GetNextNodeList_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_GetNextNodeList_Call) RunAndReturn(run func() []string) *ExecutorBackedNodeInterfaceMock_GetNextNodeList_Call {
	_c.Call.Return(run)
	return _c
}

// GetPreviousNodeList provides a mock function for the type ExecutorBackedNodeInterfaceMock
func (_mock *ExecutorBackedNodeInterfaceMock) GetPreviousNodeList() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPreviousNodeList")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// ExecutorBackedNodeInterfaceMock_GetPreviousNodeList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPreviousNodeList'
type ExecutorBackedNodeInterfaceMock_GetPreviousNodeList_Call struct {
	*mock.Call
}

// GetPreviousNodeList is a helper method to define mock.On call
func (_e *ExecutorBackedNodeInterfaceMock_Expecter) GetPreviousNodeList() *ExecutorBackedNodeInterfaceMock_GetPreviousNodeList_Call {
	return &ExecutorBackedNodeInterfaceMock_GetPreviousNodeList_Call{Call: _e.mock.On("GetPreviousNodeList")}
}

func (_c *ExecutorBackedNodeInterfaceMock_GetPreviousNodeList_Call) Run(run func()) *ExecutorBackedNodeInterfaceMock_GetPreviousNodeList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_GetPreviousNodeList_Call) Return(strings []string) *ExecutorBackedNodeInterfaceMock_GetPreviousNodeList_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_GetPreviousNodeList_Call) RunAndReturn(run func() []string) *ExecutorBackedNodeInterfaceMock_GetPreviousNodeList_Call {
	_c.Call.Return(run)
	return _c
}

// GetProperties provides a mock function for the type ExecutorBackedNodeInterfaceMock
func (_mock *ExecutorBackedNodeInterfaceMock) GetProperties() map[string]string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProperties")
	}

	var r0 map[string]string
	if returnFunc, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	return r0
}

// ExecutorBackedNodeInterfaceMock_GetProperties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProperties'
type ExecutorBackedNodeInterfaceMock_GetProperties_Call struct {
	*mock.Call
}

// GetProperties is a helper method to define mock.On call
func (_e *ExecutorBackedNodeInterfaceMock_Expecter) GetProperties() *ExecutorBackedNodeInterfaceMock_GetProperties_Call {
	return &ExecutorBackedNodeInterfaceMock_GetProperties_Call{Call: _e.mock.On("GetProperties")}
}

func (_c *ExecutorBackedNodeInterfaceMock_GetProperties_Call) Run(run func()) *ExecutorBackedNodeInterfaceMock_GetProperties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_GetProperties_Call) Return(stringToString map[string]string) *ExecutorBackedNodeInterfaceMock_GetProperties_Call {
	_c.Call.Return(stringToString)
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_GetProperties_Call) RunAndReturn(run func() map[string]string) *ExecutorBackedNodeInterfaceMock_GetProperties_Call {
	_c.Call.Return(run)
	return _c
}

// GetType provides a mock function for the type ExecutorBackedNodeInterfaceMock
func (_mock *ExecutorBackedNodeInterfaceMock) GetType() common.NodeType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetType")
	}

	var r0 common.NodeType
	if returnFunc, ok := ret.Get(0).(func() common.NodeType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(common.NodeType)
	}
	return r0
}

// ExecutorBackedNodeInterfaceMock_GetType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetType'
type ExecutorBackedNodeInterfaceMock_GetType_Call struct {
	*mock.Call
}

// GetType is a helper method to define mock.On call
func (_e *ExecutorBackedNodeInterfaceMock_Expecter) GetType() *ExecutorBackedNodeInterfaceMock_GetType_Call {
	return &ExecutorBackedNodeInterfaceMock_GetType_Call{Call: _e.mock.On("GetType")}
}

func (_c *ExecutorBackedNodeInterfaceMock_GetType_Call) Run(run func()) *ExecutorBackedNodeInterfaceMock_GetType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_GetType_Call) Return(nodeType common.NodeType) *ExecutorBackedNodeInterfaceMock_GetType_Call {
	_c.Call.Return(nodeType)
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_GetType_Call) RunAndReturn(run func() common.NodeType) *ExecutorBackedNodeInterfaceMock_GetType_Call {
	_c.Call.Return(run)
	return _c
}

// IsFinalNode provides a mock function for the type ExecutorBackedNodeInterfaceMock
func (_mock *ExecutorBackedNodeInterfaceMock) IsFinalNode() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsFinalNode")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ExecutorBackedNodeInterfaceMock_IsFinalNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFinalNode'
type ExecutorBackedNodeInterfaceMock_IsFinalNode_Call struct {
	*mock.Call
}

// IsFinalNode is a helper method to define mock.On call
func (_e *ExecutorBackedNodeInterfaceMock_Expecter) IsFinalNode() *ExecutorBackedNodeInterfaceMock_IsFinalNode_Call {
	return &ExecutorBackedNodeInterfaceMock_IsFinalNode_Call{Call: _e.mock.On("IsFinalNode")}
}

func (_c *ExecutorBackedNodeInterfaceMock_IsFinalNode_Call) Run(run func()) *ExecutorBackedNodeInterfaceMock_IsFinalNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_IsFinalNode_Call) Return(b bool) *ExecutorBackedNodeInterfaceMock_IsFinalNode_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_IsFinalNode_Call) RunAndReturn(run func() bool) *ExecutorBackedNodeInterfaceMock_IsFinalNode_Call {
	_c.Call.Return(run)
	return _c
}

// IsStartNode provides a mock function for the type ExecutorBackedNodeInterfaceMock
func (_mock *ExecutorBackedNodeInterfaceMock) IsStartNode() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsStartNode")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ExecutorBackedNodeInterfaceMock_IsStartNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsStartNode'
type ExecutorBackedNodeInterfaceMock_IsStartNode_Call struct {
	*mock.Call
}

// IsStartNode is a helper method to define mock.On call
func (_e *ExecutorBackedNodeInterfaceMock_Expecter) IsStartNode() *ExecutorBackedNodeInterfaceMock_IsStartNode_Call {
	return &ExecutorBackedNodeInterfaceMock_IsStartNode_Call{Call: _e.mock.On("IsStartNode")}
}

func (_c *ExecutorBackedNodeInterfaceMock_IsStartNode_Call) Run(run func()) *ExecutorBackedNodeInterfaceMock_IsStartNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_IsStartNode_Call) Return(b bool) *ExecutorBackedNodeInterfaceMock_IsStartNode_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_IsStartNode_Call) RunAndReturn(run func() bool) *ExecutorBackedNodeInterfaceMock_IsStartNode_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveNextNodeID provides a mock function for the type ExecutorBackedNodeInterfaceMock
func (_mock *ExecutorBackedNodeInterfaceMock) RemoveNextNodeID(nextNodeID string) {
	_mock.Called(nextNodeID)
	return
}

// ExecutorBackedNodeInterfaceMock_RemoveNextNodeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveNextNodeID'
type ExecutorBackedNodeInterfaceMock_RemoveNextNodeID_Call struct {
	*mock.Call
}

// RemoveNextNodeID is a helper method to define mock.On call
//   - nextNodeID string
func (_e *ExecutorBackedNodeInterfaceMock_Expecter) RemoveNextNodeID(nextNodeID interface{}) *ExecutorBackedNodeInterfaceMock_RemoveNextNodeID_Call {
	return &ExecutorBackedNodeInterfaceMock_RemoveNextNodeID_Call{Call: _e.mock.On("RemoveNextNodeID", nextNodeID)}
}

func (_c *ExecutorBackedNodeInterfaceMock_RemoveNextNodeID_Call) Run(run func(nextNodeID string)) *ExecutorBackedNodeInterfaceMock_RemoveNextNodeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_RemoveNextNodeID_Call) Return() *ExecutorBackedNodeInterfaceMock_RemoveNextNodeID_Call {
	_c.Call.Return()
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_RemoveNextNodeID_Call) RunAndReturn(run func(nextNodeID string)) *ExecutorBackedNodeInterfaceMock_RemoveNextNodeID_Call {
	_c.Run(run)
	return _c
}

// RemovePreviousNodeID provides a mock function for the type ExecutorBackedNodeInterfaceMock
func (_mock *ExecutorBackedNodeInterfaceMock) RemovePreviousNodeID(previousNodeID string) {
	_mock.Called(previousNodeID)
	return
}

// ExecutorBackedNodeInterfaceMock_RemovePreviousNodeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePreviousNodeID'
type ExecutorBackedNodeInterfaceMock_RemovePreviousNodeID_Call struct {
	*mock.Call
}

// RemovePreviousNodeID is a helper method to define mock.On call
//   - previousNodeID string
func (_e *ExecutorBackedNodeInterfaceMock_Expecter) RemovePreviousNodeID(previousNodeID interface{}) *ExecutorBackedNodeInterfaceMock_RemovePreviousNodeID_Call {
	return &ExecutorBackedNodeInterfaceMock_RemovePreviousNodeID_Call{Call: _e.mock.On("RemovePreviousNodeID", previousNodeID)}
}

func (_c *ExecutorBackedNodeInterfaceMock_RemovePreviousNodeID_Call) Run(run func(previousNodeID string)) *ExecutorBackedNodeInterfaceMock_RemovePreviousNodeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_RemovePreviousNodeID_Call) Return() *ExecutorBackedNodeInterfaceMock_RemovePreviousNodeID_Call {
	_c.Call.Return()
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_RemovePreviousNodeID_Call) RunAndReturn(run func(previousNodeID string)) *ExecutorBackedNodeInterfaceMock_RemovePreviousNodeID_Call {
	_c.Run(run)
	return _c
}

// SetAsFinalNode provides a mock function for the type ExecutorBackedNodeInterfaceMock
func (_mock *ExecutorBackedNodeInterfaceMock) SetAsFinalNode() {
	_mock.Called()
	return
}

// ExecutorBackedNodeInterfaceMock_SetAsFinalNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAsFinalNode'
type ExecutorBackedNodeInterfaceMock_SetAsFinalNode_Call struct {
	*mock.Call
}

// SetAsFinalNode is a helper method to define mock.On call
func (_e *ExecutorBackedNodeInterfaceMock_Expecter) SetAsFinalNode() *ExecutorBackedNodeInterfaceMock_SetAsFinalNode_Call {
	return &ExecutorBackedNodeInterfaceMock_SetAsFinalNode_Call{Call: _e.mock.On("SetAsFinalNode")}
}

func (_c *ExecutorBackedNodeInterfaceMock_SetAsFinalNode_Call) Run(run func()) *ExecutorBackedNodeInterfaceMock_SetAsFinalNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_SetAsFinalNode_Call) Return() *ExecutorBackedNodeInterfaceMock_SetAsFinalNode_Call {
	_c.Call.Return()
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_SetAsFinalNode_Call) RunAndReturn(run func()) *ExecutorBackedNodeInterfaceMock_SetAsFinalNode_Call {
	_c.Run(run)
	return _c
}

// SetAsStartNode provides a mock function for the type ExecutorBackedNodeInterfaceMock
func (_mock *ExecutorBackedNodeInterfaceMock) SetAsStartNode() {
	_mock.Called()
	return
}

// ExecutorBackedNodeInterfaceMock_SetAsStartNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAsStartNode'
type ExecutorBackedNodeInterfaceMock_SetAsStartNode_Call struct {
	*mock.Call
}

// SetAsStartNode is a helper method to define mock.On call
func (_e *ExecutorBackedNodeInterfaceMock_Expecter) SetAsStartNode() *ExecutorBackedNodeInterfaceMock_SetAsStartNode_Call {
	return &ExecutorBackedNodeInterfaceMock_SetAsStartNode_Call{Call: _e.mock.On("SetAsStartNode")}
}

func (_c *ExecutorBackedNodeInterfaceMock_SetAsStartNode_Call) Run(run func()) *ExecutorBackedNodeInterfaceMock_SetAsStartNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_SetAsStartNode_Call) Return() *ExecutorBackedNodeInterfaceMock_SetAsStartNode_Call {
	_c.Call.Return()
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_SetAsStartNode_Call) RunAndReturn(run func()) *ExecutorBackedNodeInterfaceMock_SetAsStartNode_Call {
	_c.Run(run)
	return _c
}

// SetExecutor provides a mock function for the type ExecutorBackedNodeInterfaceMock
func (_mock *ExecutorBackedNodeInterfaceMock) SetExecutor(executor ExecutorInterface) {
	_mock.Called(executor)
	return
}

// ExecutorBackedNodeInterfaceMock_SetExecutor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetExecutor'
type ExecutorBackedNodeInterfaceMock_SetExecutor_Call struct {
	*mock.Call
}

// SetExecutor is a helper method to define mock.On call
//   - executor ExecutorInterface
func (_e *ExecutorBackedNodeInterfaceMock_Expecter) SetExecutor(executor interface{}) *ExecutorBackedNodeInterfaceMock_SetExecutor_Call {
	return &ExecutorBackedNodeInterfaceMock_SetExecutor_Call{Call: _e.mock.On("SetExecutor", executor)}
}

func (_c *ExecutorBackedNodeInterfaceMock_SetExecutor_Call) Run(run func(executor ExecutorInterface)) *ExecutorBackedNodeInterfaceMock_SetExecutor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ExecutorInterface
		if args[0] != nil {
			arg0 = args[0].(ExecutorInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_SetExecutor_Call) Return() *ExecutorBackedNodeInterfaceMock_SetExecutor_Call {
	_c.Call.Return()
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_SetExecutor_Call) RunAndReturn(run func(executor ExecutorInterface)) *ExecutorBackedNodeInterfaceMock_SetExecutor_Call {
	_c.Run(run)
	return _c
}

// SetExecutorName provides a mock function for the type ExecutorBackedNodeInterfaceMock
func (_mock *ExecutorBackedNodeInterfaceMock) SetExecutorName(name string) {
	_mock.Called(name)
	return
}

// ExecutorBackedNodeInterfaceMock_SetExecutorName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetExecutorName'
type ExecutorBackedNodeInterfaceMock_SetExecutorName_Call struct {
	*mock.Call
}

// SetExecutorName is a helper method to define mock.On call
//   - name string
func (_e *ExecutorBackedNodeInterfaceMock_Expecter) SetExecutorName(name interface{}) *ExecutorBackedNodeInterfaceMock_SetExecutorName_Call {
	return &ExecutorBackedNodeInterfaceMock_SetExecutorName_Call{Call: _e.mock.On("SetExecutorName", name)}
}

func (_c *ExecutorBackedNodeInterfaceMock_SetExecutorName_Call) Run(run func(name string)) *ExecutorBackedNodeInterfaceMock_SetExecutorName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_SetExecutorName_Call) Return() *ExecutorBackedNodeInterfaceMock_SetExecutorName_Call {
	_c.Call.Return()
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_SetExecutorName_Call) RunAndReturn(run func(name string)) *ExecutorBackedNodeInterfaceMock_SetExecutorName_Call {
	_c.Run(run)
	return _c
}

// SetInputData provides a mock function for the type ExecutorBackedNodeInterfaceMock
func (_mock *ExecutorBackedNodeInterfaceMock) SetInputData(inputData []common.InputData) {
	_mock.Called(inputData)
	return
}

// ExecutorBackedNodeInterfaceMock_SetInputData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetInputData'
type ExecutorBackedNodeInterfaceMock_SetInputData_Call struct {
	*mock.Call
}

// SetInputData is a helper method to define mock.On call
//   - inputData []common.InputData
func (_e *ExecutorBackedNodeInterfaceMock_Expecter) SetInputData(inputData interface{}) *ExecutorBackedNodeInterfaceMock_SetInputData_Call {
	return &ExecutorBackedNodeInterfaceMock_SetInputData_Call{Call: _e.mock.On("SetInputData", inputData)}
}

func (_c *ExecutorBackedNodeInterfaceMock_SetInputData_Call) Run(run func(inputData []common.InputData)) *ExecutorBackedNodeInterfaceMock_SetInputData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []common.InputData
		if args[0] != nil {
			arg0 = args[0].([]common.InputData)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_SetInputData_Call) Return() *ExecutorBackedNodeInterfaceMock_SetInputData_Call {
	_c.Call.Return()
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_SetInputData_Call) RunAndReturn(run func(inputData []common.InputData)) *ExecutorBackedNodeInterfaceMock_SetInputData_Call {
	_c.Run(run)
	return _c
}

// SetNextNodeList provides a mock function for the type ExecutorBackedNodeInterfaceMock
func (_mock *ExecutorBackedNodeInterfaceMock) SetNextNodeList(nextNodeIDList []string) {
	_mock.Called(nextNodeIDList)
	return
}

// ExecutorBackedNodeInterfaceMock_SetNextNodeList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNextNodeList'
type ExecutorBackedNodeInterfaceMock_SetNextNodeList_Call struct {
	*mock.Call
}

// SetNextNodeList is a helper method to define mock.On call
//   - nextNodeIDList []string
func (_e *ExecutorBackedNodeInterfaceMock_Expecter) SetNextNodeList(nextNodeIDList interface{}) *ExecutorBackedNodeInterfaceMock_SetNextNodeList_Call {
	return &ExecutorBackedNodeInterfaceMock_SetNextNodeList_Call{Call: _e.mock.On("SetNextNodeList", nextNodeIDList)}
}

func (_c *ExecutorBackedNodeInterfaceMock_SetNextNodeList_Call) Run(run func(nextNodeIDList []string)) *ExecutorBackedNodeInterfaceMock_SetNextNodeList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_SetNextNodeList_Call) Return() *ExecutorBackedNodeInterfaceMock_SetNextNodeList_Call {
	_c.Call.Return()
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_SetNextNodeList_Call) RunAndReturn(run func(nextNodeIDList []string)) *ExecutorBackedNodeInterfaceMock_SetNextNodeList_Call {
	_c.Run(run)
	return _c
}

// SetPreviousNodeList provides a mock function for the type ExecutorBackedNodeInterfaceMock
func (_mock *ExecutorBackedNodeInterfaceMock) SetPreviousNodeList(previousNodeIDList []string) {
	_mock.Called(previousNodeIDList)
	return
}

// ExecutorBackedNodeInterfaceMock_SetPreviousNodeList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPreviousNodeList'
type ExecutorBackedNodeInterfaceMock_SetPreviousNodeList_Call struct {
	*mock.Call
}

// SetPreviousNodeList is a helper method to define mock.On call
//   - previousNodeIDList []string
func (_e *ExecutorBackedNodeInterfaceMock_Expecter) SetPreviousNodeList(previousNodeIDList interface{}) *ExecutorBackedNodeInterfaceMock_SetPreviousNodeList_Call {
	return &ExecutorBackedNodeInterfaceMock_SetPreviousNodeList_Call{Call: _e.mock.On("SetPreviousNodeList", previousNodeIDList)}
}

func (_c *ExecutorBackedNodeInterfaceMock_SetPreviousNodeList_Call) Run(run func(previousNodeIDList []string)) *ExecutorBackedNodeInterfaceMock_SetPreviousNodeList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_SetPreviousNodeList_Call) Return() *ExecutorBackedNodeInterfaceMock_SetPreviousNodeList_Call {
	_c.Call.Return()
	return _c
}

func (_c *ExecutorBackedNodeInterfaceMock_SetPreviousNodeList_Call) RunAndReturn(run func(previousNodeIDList []string)) *ExecutorBackedNodeInterfaceMock_SetPreviousNodeList_Call {
	_c.Run(run)
	return _c
}
