// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package flowmgtmock

import (
	"github.com/asgardeo/thunder/internal/flow/common"
	"github.com/asgardeo/thunder/internal/flow/mgt"
	mock "github.com/stretchr/testify/mock"
)

// newFlowStoreInterfaceMock creates a new instance of flowStoreInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newFlowStoreInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *flowStoreInterfaceMock {
	mock := &flowStoreInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// flowStoreInterfaceMock is an autogenerated mock type for the flowStoreInterface type
type flowStoreInterfaceMock struct {
	mock.Mock
}

type flowStoreInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *flowStoreInterfaceMock) EXPECT() *flowStoreInterfaceMock_Expecter {
	return &flowStoreInterfaceMock_Expecter{mock: &_m.Mock}
}

// CreateFlow provides a mock function for the type flowStoreInterfaceMock
func (_mock *flowStoreInterfaceMock) CreateFlow(flowID string, flow *flowmgt.FlowDefinition) (*flowmgt.CompleteFlowDefinition, error) {
	ret := _mock.Called(flowID, flow)

	if len(ret) == 0 {
		panic("no return value specified for CreateFlow")
	}

	var r0 *flowmgt.CompleteFlowDefinition
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *flowmgt.FlowDefinition) (*flowmgt.CompleteFlowDefinition, error)); ok {
		return returnFunc(flowID, flow)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *flowmgt.FlowDefinition) *flowmgt.CompleteFlowDefinition); ok {
		r0 = returnFunc(flowID, flow)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flowmgt.CompleteFlowDefinition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *flowmgt.FlowDefinition) error); ok {
		r1 = returnFunc(flowID, flow)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// flowStoreInterfaceMock_CreateFlow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFlow'
type flowStoreInterfaceMock_CreateFlow_Call struct {
	*mock.Call
}

// CreateFlow is a helper method to define mock.On call
//   - flowID string
//   - flow *flowmgt.FlowDefinition
func (_e *flowStoreInterfaceMock_Expecter) CreateFlow(flowID interface{}, flow interface{}) *flowStoreInterfaceMock_CreateFlow_Call {
	return &flowStoreInterfaceMock_CreateFlow_Call{Call: _e.mock.On("CreateFlow", flowID, flow)}
}

func (_c *flowStoreInterfaceMock_CreateFlow_Call) Run(run func(flowID string, flow *flowmgt.FlowDefinition)) *flowStoreInterfaceMock_CreateFlow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *flowmgt.FlowDefinition
		if args[1] != nil {
			arg1 = args[1].(*flowmgt.FlowDefinition)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *flowStoreInterfaceMock_CreateFlow_Call) Return(completeFlowDefinition *flowmgt.CompleteFlowDefinition, err error) *flowStoreInterfaceMock_CreateFlow_Call {
	_c.Call.Return(completeFlowDefinition, err)
	return _c
}

func (_c *flowStoreInterfaceMock_CreateFlow_Call) RunAndReturn(run func(flowID string, flow *flowmgt.FlowDefinition) (*flowmgt.CompleteFlowDefinition, error)) *flowStoreInterfaceMock_CreateFlow_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFlow provides a mock function for the type flowStoreInterfaceMock
func (_mock *flowStoreInterfaceMock) DeleteFlow(flowID string) error {
	ret := _mock.Called(flowID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFlow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(flowID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// flowStoreInterfaceMock_DeleteFlow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFlow'
type flowStoreInterfaceMock_DeleteFlow_Call struct {
	*mock.Call
}

// DeleteFlow is a helper method to define mock.On call
//   - flowID string
func (_e *flowStoreInterfaceMock_Expecter) DeleteFlow(flowID interface{}) *flowStoreInterfaceMock_DeleteFlow_Call {
	return &flowStoreInterfaceMock_DeleteFlow_Call{Call: _e.mock.On("DeleteFlow", flowID)}
}

func (_c *flowStoreInterfaceMock_DeleteFlow_Call) Run(run func(flowID string)) *flowStoreInterfaceMock_DeleteFlow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *flowStoreInterfaceMock_DeleteFlow_Call) Return(err error) *flowStoreInterfaceMock_DeleteFlow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *flowStoreInterfaceMock_DeleteFlow_Call) RunAndReturn(run func(flowID string) error) *flowStoreInterfaceMock_DeleteFlow_Call {
	_c.Call.Return(run)
	return _c
}

// GetFlowByHandle provides a mock function for the type flowStoreInterfaceMock
func (_mock *flowStoreInterfaceMock) GetFlowByHandle(handle string, flowType common.FlowType) (*flowmgt.CompleteFlowDefinition, error) {
	ret := _mock.Called(handle, flowType)

	if len(ret) == 0 {
		panic("no return value specified for GetFlowByHandle")
	}

	var r0 *flowmgt.CompleteFlowDefinition
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, common.FlowType) (*flowmgt.CompleteFlowDefinition, error)); ok {
		return returnFunc(handle, flowType)
	}
	if returnFunc, ok := ret.Get(0).(func(string, common.FlowType) *flowmgt.CompleteFlowDefinition); ok {
		r0 = returnFunc(handle, flowType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flowmgt.CompleteFlowDefinition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, common.FlowType) error); ok {
		r1 = returnFunc(handle, flowType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// flowStoreInterfaceMock_GetFlowByHandle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlowByHandle'
type flowStoreInterfaceMock_GetFlowByHandle_Call struct {
	*mock.Call
}

// GetFlowByHandle is a helper method to define mock.On call
//   - handle string
//   - flowType common.FlowType
func (_e *flowStoreInterfaceMock_Expecter) GetFlowByHandle(handle interface{}, flowType interface{}) *flowStoreInterfaceMock_GetFlowByHandle_Call {
	return &flowStoreInterfaceMock_GetFlowByHandle_Call{Call: _e.mock.On("GetFlowByHandle", handle, flowType)}
}

func (_c *flowStoreInterfaceMock_GetFlowByHandle_Call) Run(run func(handle string, flowType common.FlowType)) *flowStoreInterfaceMock_GetFlowByHandle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 common.FlowType
		if args[1] != nil {
			arg1 = args[1].(common.FlowType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *flowStoreInterfaceMock_GetFlowByHandle_Call) Return(completeFlowDefinition *flowmgt.CompleteFlowDefinition, err error) *flowStoreInterfaceMock_GetFlowByHandle_Call {
	_c.Call.Return(completeFlowDefinition, err)
	return _c
}

func (_c *flowStoreInterfaceMock_GetFlowByHandle_Call) RunAndReturn(run func(handle string, flowType common.FlowType) (*flowmgt.CompleteFlowDefinition, error)) *flowStoreInterfaceMock_GetFlowByHandle_Call {
	_c.Call.Return(run)
	return _c
}

// GetFlowByID provides a mock function for the type flowStoreInterfaceMock
func (_mock *flowStoreInterfaceMock) GetFlowByID(flowID string) (*flowmgt.CompleteFlowDefinition, error) {
	ret := _mock.Called(flowID)

	if len(ret) == 0 {
		panic("no return value specified for GetFlowByID")
	}

	var r0 *flowmgt.CompleteFlowDefinition
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*flowmgt.CompleteFlowDefinition, error)); ok {
		return returnFunc(flowID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *flowmgt.CompleteFlowDefinition); ok {
		r0 = returnFunc(flowID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flowmgt.CompleteFlowDefinition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(flowID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// flowStoreInterfaceMock_GetFlowByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlowByID'
type flowStoreInterfaceMock_GetFlowByID_Call struct {
	*mock.Call
}

// GetFlowByID is a helper method to define mock.On call
//   - flowID string
func (_e *flowStoreInterfaceMock_Expecter) GetFlowByID(flowID interface{}) *flowStoreInterfaceMock_GetFlowByID_Call {
	return &flowStoreInterfaceMock_GetFlowByID_Call{Call: _e.mock.On("GetFlowByID", flowID)}
}

func (_c *flowStoreInterfaceMock_GetFlowByID_Call) Run(run func(flowID string)) *flowStoreInterfaceMock_GetFlowByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *flowStoreInterfaceMock_GetFlowByID_Call) Return(completeFlowDefinition *flowmgt.CompleteFlowDefinition, err error) *flowStoreInterfaceMock_GetFlowByID_Call {
	_c.Call.Return(completeFlowDefinition, err)
	return _c
}

func (_c *flowStoreInterfaceMock_GetFlowByID_Call) RunAndReturn(run func(flowID string) (*flowmgt.CompleteFlowDefinition, error)) *flowStoreInterfaceMock_GetFlowByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFlowVersion provides a mock function for the type flowStoreInterfaceMock
func (_mock *flowStoreInterfaceMock) GetFlowVersion(flowID string, version int) (*flowmgt.FlowVersion, error) {
	ret := _mock.Called(flowID, version)

	if len(ret) == 0 {
		panic("no return value specified for GetFlowVersion")
	}

	var r0 *flowmgt.FlowVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int) (*flowmgt.FlowVersion, error)); ok {
		return returnFunc(flowID, version)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int) *flowmgt.FlowVersion); ok {
		r0 = returnFunc(flowID, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flowmgt.FlowVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = returnFunc(flowID, version)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// flowStoreInterfaceMock_GetFlowVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlowVersion'
type flowStoreInterfaceMock_GetFlowVersion_Call struct {
	*mock.Call
}

// GetFlowVersion is a helper method to define mock.On call
//   - flowID string
//   - version int
func (_e *flowStoreInterfaceMock_Expecter) GetFlowVersion(flowID interface{}, version interface{}) *flowStoreInterfaceMock_GetFlowVersion_Call {
	return &flowStoreInterfaceMock_GetFlowVersion_Call{Call: _e.mock.On("GetFlowVersion", flowID, version)}
}

func (_c *flowStoreInterfaceMock_GetFlowVersion_Call) Run(run func(flowID string, version int)) *flowStoreInterfaceMock_GetFlowVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *flowStoreInterfaceMock_GetFlowVersion_Call) Return(flowVersion *flowmgt.FlowVersion, err error) *flowStoreInterfaceMock_GetFlowVersion_Call {
	_c.Call.Return(flowVersion, err)
	return _c
}

func (_c *flowStoreInterfaceMock_GetFlowVersion_Call) RunAndReturn(run func(flowID string, version int) (*flowmgt.FlowVersion, error)) *flowStoreInterfaceMock_GetFlowVersion_Call {
	_c.Call.Return(run)
	return _c
}

// IsFlowExists provides a mock function for the type flowStoreInterfaceMock
func (_mock *flowStoreInterfaceMock) IsFlowExists(flowID string) (bool, error) {
	ret := _mock.Called(flowID)

	if len(ret) == 0 {
		panic("no return value specified for IsFlowExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(flowID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(flowID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(flowID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// flowStoreInterfaceMock_IsFlowExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFlowExists'
type flowStoreInterfaceMock_IsFlowExists_Call struct {
	*mock.Call
}

// IsFlowExists is a helper method to define mock.On call
//   - flowID string
func (_e *flowStoreInterfaceMock_Expecter) IsFlowExists(flowID interface{}) *flowStoreInterfaceMock_IsFlowExists_Call {
	return &flowStoreInterfaceMock_IsFlowExists_Call{Call: _e.mock.On("IsFlowExists", flowID)}
}

func (_c *flowStoreInterfaceMock_IsFlowExists_Call) Run(run func(flowID string)) *flowStoreInterfaceMock_IsFlowExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *flowStoreInterfaceMock_IsFlowExists_Call) Return(b bool, err error) *flowStoreInterfaceMock_IsFlowExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *flowStoreInterfaceMock_IsFlowExists_Call) RunAndReturn(run func(flowID string) (bool, error)) *flowStoreInterfaceMock_IsFlowExists_Call {
	_c.Call.Return(run)
	return _c
}

// IsFlowExistsByHandle provides a mock function for the type flowStoreInterfaceMock
func (_mock *flowStoreInterfaceMock) IsFlowExistsByHandle(handle string, flowType common.FlowType) (bool, error) {
	ret := _mock.Called(handle, flowType)

	if len(ret) == 0 {
		panic("no return value specified for IsFlowExistsByHandle")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, common.FlowType) (bool, error)); ok {
		return returnFunc(handle, flowType)
	}
	if returnFunc, ok := ret.Get(0).(func(string, common.FlowType) bool); ok {
		r0 = returnFunc(handle, flowType)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, common.FlowType) error); ok {
		r1 = returnFunc(handle, flowType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// flowStoreInterfaceMock_IsFlowExistsByHandle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFlowExistsByHandle'
type flowStoreInterfaceMock_IsFlowExistsByHandle_Call struct {
	*mock.Call
}

// IsFlowExistsByHandle is a helper method to define mock.On call
//   - handle string
//   - flowType common.FlowType
func (_e *flowStoreInterfaceMock_Expecter) IsFlowExistsByHandle(handle interface{}, flowType interface{}) *flowStoreInterfaceMock_IsFlowExistsByHandle_Call {
	return &flowStoreInterfaceMock_IsFlowExistsByHandle_Call{Call: _e.mock.On("IsFlowExistsByHandle", handle, flowType)}
}

func (_c *flowStoreInterfaceMock_IsFlowExistsByHandle_Call) Run(run func(handle string, flowType common.FlowType)) *flowStoreInterfaceMock_IsFlowExistsByHandle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 common.FlowType
		if args[1] != nil {
			arg1 = args[1].(common.FlowType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *flowStoreInterfaceMock_IsFlowExistsByHandle_Call) Return(b bool, err error) *flowStoreInterfaceMock_IsFlowExistsByHandle_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *flowStoreInterfaceMock_IsFlowExistsByHandle_Call) RunAndReturn(run func(handle string, flowType common.FlowType) (bool, error)) *flowStoreInterfaceMock_IsFlowExistsByHandle_Call {
	_c.Call.Return(run)
	return _c
}

// ListFlowVersions provides a mock function for the type flowStoreInterfaceMock
func (_mock *flowStoreInterfaceMock) ListFlowVersions(flowID string) ([]flowmgt.BasicFlowVersion, error) {
	ret := _mock.Called(flowID)

	if len(ret) == 0 {
		panic("no return value specified for ListFlowVersions")
	}

	var r0 []flowmgt.BasicFlowVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]flowmgt.BasicFlowVersion, error)); ok {
		return returnFunc(flowID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []flowmgt.BasicFlowVersion); ok {
		r0 = returnFunc(flowID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]flowmgt.BasicFlowVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(flowID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// flowStoreInterfaceMock_ListFlowVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFlowVersions'
type flowStoreInterfaceMock_ListFlowVersions_Call struct {
	*mock.Call
}

// ListFlowVersions is a helper method to define mock.On call
//   - flowID string
func (_e *flowStoreInterfaceMock_Expecter) ListFlowVersions(flowID interface{}) *flowStoreInterfaceMock_ListFlowVersions_Call {
	return &flowStoreInterfaceMock_ListFlowVersions_Call{Call: _e.mock.On("ListFlowVersions", flowID)}
}

func (_c *flowStoreInterfaceMock_ListFlowVersions_Call) Run(run func(flowID string)) *flowStoreInterfaceMock_ListFlowVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *flowStoreInterfaceMock_ListFlowVersions_Call) Return(basicFlowVersions []flowmgt.BasicFlowVersion, err error) *flowStoreInterfaceMock_ListFlowVersions_Call {
	_c.Call.Return(basicFlowVersions, err)
	return _c
}

func (_c *flowStoreInterfaceMock_ListFlowVersions_Call) RunAndReturn(run func(flowID string) ([]flowmgt.BasicFlowVersion, error)) *flowStoreInterfaceMock_ListFlowVersions_Call {
	_c.Call.Return(run)
	return _c
}

// ListFlows provides a mock function for the type flowStoreInterfaceMock
func (_mock *flowStoreInterfaceMock) ListFlows(limit int, offset int, flowType string) ([]flowmgt.BasicFlowDefinition, int, error) {
	ret := _mock.Called(limit, offset, flowType)

	if len(ret) == 0 {
		panic("no return value specified for ListFlows")
	}

	var r0 []flowmgt.BasicFlowDefinition
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(int, int, string) ([]flowmgt.BasicFlowDefinition, int, error)); ok {
		return returnFunc(limit, offset, flowType)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int, string) []flowmgt.BasicFlowDefinition); ok {
		r0 = returnFunc(limit, offset, flowType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]flowmgt.BasicFlowDefinition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int, string) int); ok {
		r1 = returnFunc(limit, offset, flowType)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(int, int, string) error); ok {
		r2 = returnFunc(limit, offset, flowType)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// flowStoreInterfaceMock_ListFlows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFlows'
type flowStoreInterfaceMock_ListFlows_Call struct {
	*mock.Call
}

// ListFlows is a helper method to define mock.On call
//   - limit int
//   - offset int
//   - flowType string
func (_e *flowStoreInterfaceMock_Expecter) ListFlows(limit interface{}, offset interface{}, flowType interface{}) *flowStoreInterfaceMock_ListFlows_Call {
	return &flowStoreInterfaceMock_ListFlows_Call{Call: _e.mock.On("ListFlows", limit, offset, flowType)}
}

func (_c *flowStoreInterfaceMock_ListFlows_Call) Run(run func(limit int, offset int, flowType string)) *flowStoreInterfaceMock_ListFlows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *flowStoreInterfaceMock_ListFlows_Call) Return(basicFlowDefinitions []flowmgt.BasicFlowDefinition, n int, err error) *flowStoreInterfaceMock_ListFlows_Call {
	_c.Call.Return(basicFlowDefinitions, n, err)
	return _c
}

func (_c *flowStoreInterfaceMock_ListFlows_Call) RunAndReturn(run func(limit int, offset int, flowType string) ([]flowmgt.BasicFlowDefinition, int, error)) *flowStoreInterfaceMock_ListFlows_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreFlowVersion provides a mock function for the type flowStoreInterfaceMock
func (_mock *flowStoreInterfaceMock) RestoreFlowVersion(flowID string, version int) (*flowmgt.CompleteFlowDefinition, error) {
	ret := _mock.Called(flowID, version)

	if len(ret) == 0 {
		panic("no return value specified for RestoreFlowVersion")
	}

	var r0 *flowmgt.CompleteFlowDefinition
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int) (*flowmgt.CompleteFlowDefinition, error)); ok {
		return returnFunc(flowID, version)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int) *flowmgt.CompleteFlowDefinition); ok {
		r0 = returnFunc(flowID, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flowmgt.CompleteFlowDefinition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = returnFunc(flowID, version)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// flowStoreInterfaceMock_RestoreFlowVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreFlowVersion'
type flowStoreInterfaceMock_RestoreFlowVersion_Call struct {
	*mock.Call
}

// RestoreFlowVersion is a helper method to define mock.On call
//   - flowID string
//   - version int
func (_e *flowStoreInterfaceMock_Expecter) RestoreFlowVersion(flowID interface{}, version interface{}) *flowStoreInterfaceMock_RestoreFlowVersion_Call {
	return &flowStoreInterfaceMock_RestoreFlowVersion_Call{Call: _e.mock.On("RestoreFlowVersion", flowID, version)}
}

func (_c *flowStoreInterfaceMock_RestoreFlowVersion_Call) Run(run func(flowID string, version int)) *flowStoreInterfaceMock_RestoreFlowVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *flowStoreInterfaceMock_RestoreFlowVersion_Call) Return(completeFlowDefinition *flowmgt.CompleteFlowDefinition, err error) *flowStoreInterfaceMock_RestoreFlowVersion_Call {
	_c.Call.Return(completeFlowDefinition, err)
	return _c
}

func (_c *flowStoreInterfaceMock_RestoreFlowVersion_Call) RunAndReturn(run func(flowID string, version int) (*flowmgt.CompleteFlowDefinition, error)) *flowStoreInterfaceMock_RestoreFlowVersion_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFlow provides a mock function for the type flowStoreInterfaceMock
func (_mock *flowStoreInterfaceMock) UpdateFlow(flowID string, flow *flowmgt.FlowDefinition) (*flowmgt.CompleteFlowDefinition, error) {
	ret := _mock.Called(flowID, flow)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFlow")
	}

	var r0 *flowmgt.CompleteFlowDefinition
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *flowmgt.FlowDefinition) (*flowmgt.CompleteFlowDefinition, error)); ok {
		return returnFunc(flowID, flow)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *flowmgt.FlowDefinition) *flowmgt.CompleteFlowDefinition); ok {
		r0 = returnFunc(flowID, flow)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flowmgt.CompleteFlowDefinition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *flowmgt.FlowDefinition) error); ok {
		r1 = returnFunc(flowID, flow)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// flowStoreInterfaceMock_UpdateFlow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFlow'
type flowStoreInterfaceMock_UpdateFlow_Call struct {
	*mock.Call
}

// UpdateFlow is a helper method to define mock.On call
//   - flowID string
//   - flow *flowmgt.FlowDefinition
func (_e *flowStoreInterfaceMock_Expecter) UpdateFlow(flowID interface{}, flow interface{}) *flowStoreInterfaceMock_UpdateFlow_Call {
	return &flowStoreInterfaceMock_UpdateFlow_Call{Call: _e.mock.On("UpdateFlow", flowID, flow)}
}

func (_c *flowStoreInterfaceMock_UpdateFlow_Call) Run(run func(flowID string, flow *flowmgt.FlowDefinition)) *flowStoreInterfaceMock_UpdateFlow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *flowmgt.FlowDefinition
		if args[1] != nil {
			arg1 = args[1].(*flowmgt.FlowDefinition)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *flowStoreInterfaceMock_UpdateFlow_Call) Return(completeFlowDefinition *flowmgt.CompleteFlowDefinition, err error) *flowStoreInterfaceMock_UpdateFlow_Call {
	_c.Call.Return(completeFlowDefinition, err)
	return _c
}

func (_c *flowStoreInterfaceMock_UpdateFlow_Call) RunAndReturn(run func(flowID string, flow *flowmgt.FlowDefinition) (*flowmgt.CompleteFlowDefinition, error)) *flowStoreInterfaceMock_UpdateFlow_Call {
	_c.Call.Return(run)
	return _c
}
