-- Table to store OAuth2 authorization codes.
CREATE TABLE AUTHORIZATION_CODE (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    CODE_ID VARCHAR(36) NOT NULL,
    AUTHORIZATION_CODE VARCHAR(500) NOT NULL,
    CLIENT_ID VARCHAR(255) NOT NULL,
    STATE VARCHAR(50) NOT NULL,
    AUTHZ_DATA JSONB NOT NULL,
    TIME_CREATED TIMESTAMP NOT NULL,
    EXPIRY_TIME TIMESTAMP NOT NULL,
    UNIQUE (CODE_ID, DEPLOYMENT_ID)
);

-- Index for deployment isolation on AUTHORIZATION_CODE
CREATE INDEX idx_authorization_code_deployment_id ON AUTHORIZATION_CODE (DEPLOYMENT_ID);

-- Table to store flow context metadata and state
CREATE TABLE FLOW_CONTEXT (
    FLOW_ID VARCHAR(36) NOT NULL,
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    APP_ID VARCHAR(36) NOT NULL,
    CURRENT_NODE_ID VARCHAR(50),
    CURRENT_ACTION_ID VARCHAR(50),
    GRAPH_ID VARCHAR(50) NOT NULL,
    RUNTIME_DATA JSONB,
    EXECUTION_HISTORY JSONB,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (FLOW_ID, DEPLOYMENT_ID)
);

-- Index for deployment isolation on FLOW_CONTEXT
CREATE INDEX idx_flow_context_deployment_id ON FLOW_CONTEXT (DEPLOYMENT_ID);

-- Table to store flow user data
CREATE TABLE FLOW_USER_DATA (
    FLOW_ID VARCHAR(36) NOT NULL,
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    IS_AUTHENTICATED BOOLEAN NOT NULL DEFAULT FALSE,
    USER_ID VARCHAR(36),
    OU_ID VARCHAR(36),
    USER_TYPE VARCHAR(50),
    USER_INPUTS JSONB,
    USER_ATTRIBUTES JSONB,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (FLOW_ID, DEPLOYMENT_ID),
    FOREIGN KEY (FLOW_ID, DEPLOYMENT_ID) REFERENCES FLOW_CONTEXT(FLOW_ID, DEPLOYMENT_ID) ON DELETE CASCADE
);

-- Index for deployment isolation on FLOW_USER_DATA
CREATE INDEX idx_flow_user_data_deployment_id ON FLOW_USER_DATA (DEPLOYMENT_ID);
