// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package userschemamock

import (
	"encoding/json"

	"github.com/asgardeo/thunder/internal/system/error/serviceerror"
	"github.com/asgardeo/thunder/internal/userschema"
	mock "github.com/stretchr/testify/mock"
)

// NewUserSchemaServiceInterfaceMock creates a new instance of UserSchemaServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserSchemaServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserSchemaServiceInterfaceMock {
	mock := &UserSchemaServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserSchemaServiceInterfaceMock is an autogenerated mock type for the UserSchemaServiceInterface type
type UserSchemaServiceInterfaceMock struct {
	mock.Mock
}

type UserSchemaServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserSchemaServiceInterfaceMock) EXPECT() *UserSchemaServiceInterfaceMock_Expecter {
	return &UserSchemaServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// CreateUserSchema provides a mock function for the type UserSchemaServiceInterfaceMock
func (_mock *UserSchemaServiceInterfaceMock) CreateUserSchema(request userschema.CreateUserSchemaRequest) (*userschema.UserSchema, *serviceerror.ServiceError) {
	ret := _mock.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserSchema")
	}

	var r0 *userschema.UserSchema
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(userschema.CreateUserSchemaRequest) (*userschema.UserSchema, *serviceerror.ServiceError)); ok {
		return returnFunc(request)
	}
	if returnFunc, ok := ret.Get(0).(func(userschema.CreateUserSchemaRequest) *userschema.UserSchema); ok {
		r0 = returnFunc(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userschema.UserSchema)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(userschema.CreateUserSchemaRequest) *serviceerror.ServiceError); ok {
		r1 = returnFunc(request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// UserSchemaServiceInterfaceMock_CreateUserSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserSchema'
type UserSchemaServiceInterfaceMock_CreateUserSchema_Call struct {
	*mock.Call
}

// CreateUserSchema is a helper method to define mock.On call
//   - request userschema.CreateUserSchemaRequest
func (_e *UserSchemaServiceInterfaceMock_Expecter) CreateUserSchema(request interface{}) *UserSchemaServiceInterfaceMock_CreateUserSchema_Call {
	return &UserSchemaServiceInterfaceMock_CreateUserSchema_Call{Call: _e.mock.On("CreateUserSchema", request)}
}

func (_c *UserSchemaServiceInterfaceMock_CreateUserSchema_Call) Run(run func(request userschema.CreateUserSchemaRequest)) *UserSchemaServiceInterfaceMock_CreateUserSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 userschema.CreateUserSchemaRequest
		if args[0] != nil {
			arg0 = args[0].(userschema.CreateUserSchemaRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_CreateUserSchema_Call) Return(userSchema *userschema.UserSchema, serviceError *serviceerror.ServiceError) *UserSchemaServiceInterfaceMock_CreateUserSchema_Call {
	_c.Call.Return(userSchema, serviceError)
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_CreateUserSchema_Call) RunAndReturn(run func(request userschema.CreateUserSchemaRequest) (*userschema.UserSchema, *serviceerror.ServiceError)) *UserSchemaServiceInterfaceMock_CreateUserSchema_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserSchema provides a mock function for the type UserSchemaServiceInterfaceMock
func (_mock *UserSchemaServiceInterfaceMock) DeleteUserSchema(schemaID string) *serviceerror.ServiceError {
	ret := _mock.Called(schemaID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserSchema")
	}

	var r0 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string) *serviceerror.ServiceError); ok {
		r0 = returnFunc(schemaID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}
	return r0
}

// UserSchemaServiceInterfaceMock_DeleteUserSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserSchema'
type UserSchemaServiceInterfaceMock_DeleteUserSchema_Call struct {
	*mock.Call
}

// DeleteUserSchema is a helper method to define mock.On call
//   - schemaID string
func (_e *UserSchemaServiceInterfaceMock_Expecter) DeleteUserSchema(schemaID interface{}) *UserSchemaServiceInterfaceMock_DeleteUserSchema_Call {
	return &UserSchemaServiceInterfaceMock_DeleteUserSchema_Call{Call: _e.mock.On("DeleteUserSchema", schemaID)}
}

func (_c *UserSchemaServiceInterfaceMock_DeleteUserSchema_Call) Run(run func(schemaID string)) *UserSchemaServiceInterfaceMock_DeleteUserSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_DeleteUserSchema_Call) Return(serviceError *serviceerror.ServiceError) *UserSchemaServiceInterfaceMock_DeleteUserSchema_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_DeleteUserSchema_Call) RunAndReturn(run func(schemaID string) *serviceerror.ServiceError) *UserSchemaServiceInterfaceMock_DeleteUserSchema_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserSchema provides a mock function for the type UserSchemaServiceInterfaceMock
func (_mock *UserSchemaServiceInterfaceMock) GetUserSchema(schemaID string) (*userschema.UserSchema, *serviceerror.ServiceError) {
	ret := _mock.Called(schemaID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSchema")
	}

	var r0 *userschema.UserSchema
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string) (*userschema.UserSchema, *serviceerror.ServiceError)); ok {
		return returnFunc(schemaID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *userschema.UserSchema); ok {
		r0 = returnFunc(schemaID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userschema.UserSchema)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(schemaID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// UserSchemaServiceInterfaceMock_GetUserSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserSchema'
type UserSchemaServiceInterfaceMock_GetUserSchema_Call struct {
	*mock.Call
}

// GetUserSchema is a helper method to define mock.On call
//   - schemaID string
func (_e *UserSchemaServiceInterfaceMock_Expecter) GetUserSchema(schemaID interface{}) *UserSchemaServiceInterfaceMock_GetUserSchema_Call {
	return &UserSchemaServiceInterfaceMock_GetUserSchema_Call{Call: _e.mock.On("GetUserSchema", schemaID)}
}

func (_c *UserSchemaServiceInterfaceMock_GetUserSchema_Call) Run(run func(schemaID string)) *UserSchemaServiceInterfaceMock_GetUserSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_GetUserSchema_Call) Return(userSchema *userschema.UserSchema, serviceError *serviceerror.ServiceError) *UserSchemaServiceInterfaceMock_GetUserSchema_Call {
	_c.Call.Return(userSchema, serviceError)
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_GetUserSchema_Call) RunAndReturn(run func(schemaID string) (*userschema.UserSchema, *serviceerror.ServiceError)) *UserSchemaServiceInterfaceMock_GetUserSchema_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserSchemaList provides a mock function for the type UserSchemaServiceInterfaceMock
func (_mock *UserSchemaServiceInterfaceMock) GetUserSchemaList(limit int, offset int) (*userschema.UserSchemaListResponse, *serviceerror.ServiceError) {
	ret := _mock.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSchemaList")
	}

	var r0 *userschema.UserSchemaListResponse
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(int, int) (*userschema.UserSchemaListResponse, *serviceerror.ServiceError)); ok {
		return returnFunc(limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) *userschema.UserSchemaListResponse); ok {
		r0 = returnFunc(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userschema.UserSchemaListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) *serviceerror.ServiceError); ok {
		r1 = returnFunc(limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// UserSchemaServiceInterfaceMock_GetUserSchemaList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserSchemaList'
type UserSchemaServiceInterfaceMock_GetUserSchemaList_Call struct {
	*mock.Call
}

// GetUserSchemaList is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *UserSchemaServiceInterfaceMock_Expecter) GetUserSchemaList(limit interface{}, offset interface{}) *UserSchemaServiceInterfaceMock_GetUserSchemaList_Call {
	return &UserSchemaServiceInterfaceMock_GetUserSchemaList_Call{Call: _e.mock.On("GetUserSchemaList", limit, offset)}
}

func (_c *UserSchemaServiceInterfaceMock_GetUserSchemaList_Call) Run(run func(limit int, offset int)) *UserSchemaServiceInterfaceMock_GetUserSchemaList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_GetUserSchemaList_Call) Return(userSchemaListResponse *userschema.UserSchemaListResponse, serviceError *serviceerror.ServiceError) *UserSchemaServiceInterfaceMock_GetUserSchemaList_Call {
	_c.Call.Return(userSchemaListResponse, serviceError)
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_GetUserSchemaList_Call) RunAndReturn(run func(limit int, offset int) (*userschema.UserSchemaListResponse, *serviceerror.ServiceError)) *UserSchemaServiceInterfaceMock_GetUserSchemaList_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserSchema provides a mock function for the type UserSchemaServiceInterfaceMock
func (_mock *UserSchemaServiceInterfaceMock) UpdateUserSchema(schemaID string, request userschema.UpdateUserSchemaRequest) (*userschema.UserSchema, *serviceerror.ServiceError) {
	ret := _mock.Called(schemaID, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserSchema")
	}

	var r0 *userschema.UserSchema
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, userschema.UpdateUserSchemaRequest) (*userschema.UserSchema, *serviceerror.ServiceError)); ok {
		return returnFunc(schemaID, request)
	}
	if returnFunc, ok := ret.Get(0).(func(string, userschema.UpdateUserSchemaRequest) *userschema.UserSchema); ok {
		r0 = returnFunc(schemaID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userschema.UserSchema)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, userschema.UpdateUserSchemaRequest) *serviceerror.ServiceError); ok {
		r1 = returnFunc(schemaID, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// UserSchemaServiceInterfaceMock_UpdateUserSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserSchema'
type UserSchemaServiceInterfaceMock_UpdateUserSchema_Call struct {
	*mock.Call
}

// UpdateUserSchema is a helper method to define mock.On call
//   - schemaID string
//   - request userschema.UpdateUserSchemaRequest
func (_e *UserSchemaServiceInterfaceMock_Expecter) UpdateUserSchema(schemaID interface{}, request interface{}) *UserSchemaServiceInterfaceMock_UpdateUserSchema_Call {
	return &UserSchemaServiceInterfaceMock_UpdateUserSchema_Call{Call: _e.mock.On("UpdateUserSchema", schemaID, request)}
}

func (_c *UserSchemaServiceInterfaceMock_UpdateUserSchema_Call) Run(run func(schemaID string, request userschema.UpdateUserSchemaRequest)) *UserSchemaServiceInterfaceMock_UpdateUserSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 userschema.UpdateUserSchemaRequest
		if args[1] != nil {
			arg1 = args[1].(userschema.UpdateUserSchemaRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_UpdateUserSchema_Call) Return(userSchema *userschema.UserSchema, serviceError *serviceerror.ServiceError) *UserSchemaServiceInterfaceMock_UpdateUserSchema_Call {
	_c.Call.Return(userSchema, serviceError)
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_UpdateUserSchema_Call) RunAndReturn(run func(schemaID string, request userschema.UpdateUserSchemaRequest) (*userschema.UserSchema, *serviceerror.ServiceError)) *UserSchemaServiceInterfaceMock_UpdateUserSchema_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateUser provides a mock function for the type UserSchemaServiceInterfaceMock
func (_mock *UserSchemaServiceInterfaceMock) ValidateUser(userType string, userAttributes json.RawMessage) (bool, *serviceerror.ServiceError) {
	ret := _mock.Called(userType, userAttributes)

	if len(ret) == 0 {
		panic("no return value specified for ValidateUser")
	}

	var r0 bool
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, json.RawMessage) (bool, *serviceerror.ServiceError)); ok {
		return returnFunc(userType, userAttributes)
	}
	if returnFunc, ok := ret.Get(0).(func(string, json.RawMessage) bool); ok {
		r0 = returnFunc(userType, userAttributes)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, json.RawMessage) *serviceerror.ServiceError); ok {
		r1 = returnFunc(userType, userAttributes)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// UserSchemaServiceInterfaceMock_ValidateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateUser'
type UserSchemaServiceInterfaceMock_ValidateUser_Call struct {
	*mock.Call
}

// ValidateUser is a helper method to define mock.On call
//   - userType string
//   - userAttributes json.RawMessage
func (_e *UserSchemaServiceInterfaceMock_Expecter) ValidateUser(userType interface{}, userAttributes interface{}) *UserSchemaServiceInterfaceMock_ValidateUser_Call {
	return &UserSchemaServiceInterfaceMock_ValidateUser_Call{Call: _e.mock.On("ValidateUser", userType, userAttributes)}
}

func (_c *UserSchemaServiceInterfaceMock_ValidateUser_Call) Run(run func(userType string, userAttributes json.RawMessage)) *UserSchemaServiceInterfaceMock_ValidateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 json.RawMessage
		if args[1] != nil {
			arg1 = args[1].(json.RawMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_ValidateUser_Call) Return(b bool, serviceError *serviceerror.ServiceError) *UserSchemaServiceInterfaceMock_ValidateUser_Call {
	_c.Call.Return(b, serviceError)
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_ValidateUser_Call) RunAndReturn(run func(userType string, userAttributes json.RawMessage) (bool, *serviceerror.ServiceError)) *UserSchemaServiceInterfaceMock_ValidateUser_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateUserUniqueness provides a mock function for the type UserSchemaServiceInterfaceMock
func (_mock *UserSchemaServiceInterfaceMock) ValidateUserUniqueness(userType string, userAttributes json.RawMessage, identifyUser func(map[string]interface{}) (*string, error)) (bool, *serviceerror.ServiceError) {
	ret := _mock.Called(userType, userAttributes, identifyUser)

	if len(ret) == 0 {
		panic("no return value specified for ValidateUserUniqueness")
	}

	var r0 bool
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, json.RawMessage, func(map[string]interface{}) (*string, error)) (bool, *serviceerror.ServiceError)); ok {
		return returnFunc(userType, userAttributes, identifyUser)
	}
	if returnFunc, ok := ret.Get(0).(func(string, json.RawMessage, func(map[string]interface{}) (*string, error)) bool); ok {
		r0 = returnFunc(userType, userAttributes, identifyUser)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, json.RawMessage, func(map[string]interface{}) (*string, error)) *serviceerror.ServiceError); ok {
		r1 = returnFunc(userType, userAttributes, identifyUser)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// UserSchemaServiceInterfaceMock_ValidateUserUniqueness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateUserUniqueness'
type UserSchemaServiceInterfaceMock_ValidateUserUniqueness_Call struct {
	*mock.Call
}

// ValidateUserUniqueness is a helper method to define mock.On call
//   - userType string
//   - userAttributes json.RawMessage
//   - identifyUser func(map[string]interface{}) (*string, error)
func (_e *UserSchemaServiceInterfaceMock_Expecter) ValidateUserUniqueness(userType interface{}, userAttributes interface{}, identifyUser interface{}) *UserSchemaServiceInterfaceMock_ValidateUserUniqueness_Call {
	return &UserSchemaServiceInterfaceMock_ValidateUserUniqueness_Call{Call: _e.mock.On("ValidateUserUniqueness", userType, userAttributes, identifyUser)}
}

func (_c *UserSchemaServiceInterfaceMock_ValidateUserUniqueness_Call) Run(run func(userType string, userAttributes json.RawMessage, identifyUser func(map[string]interface{}) (*string, error))) *UserSchemaServiceInterfaceMock_ValidateUserUniqueness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 json.RawMessage
		if args[1] != nil {
			arg1 = args[1].(json.RawMessage)
		}
		var arg2 func(map[string]interface{}) (*string, error)
		if args[2] != nil {
			arg2 = args[2].(func(map[string]interface{}) (*string, error))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_ValidateUserUniqueness_Call) Return(b bool, serviceError *serviceerror.ServiceError) *UserSchemaServiceInterfaceMock_ValidateUserUniqueness_Call {
	_c.Call.Return(b, serviceError)
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_ValidateUserUniqueness_Call) RunAndReturn(run func(userType string, userAttributes json.RawMessage, identifyUser func(map[string]interface{}) (*string, error)) (bool, *serviceerror.ServiceError)) *UserSchemaServiceInterfaceMock_ValidateUserUniqueness_Call {
	_c.Call.Return(run)
	return _c
}
