/**
 * Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import applicationApiSidebar from './docs/apis/application/sidebar';
import authenticationApiSidebar from './docs/apis/authentication/sidebar';
import brandingApiSidebar from './docs/apis/branding/sidebar';
import flowExecutionApiSidebar from './docs/apis/flow-execution/sidebar';
import flowManagementApiSidebar from './docs/apis/flow-management/sidebar';
import groupApiSidebar from './docs/apis/group/sidebar';
import healthCheckApiSidebar from './docs/apis/health-check/sidebar';
import i18nApiSidebar from './docs/apis/i18n/sidebar';
import idpApiSidebar from './docs/apis/idp/sidebar';
import notificationSenderApiSidebar from './docs/apis/notification-sender/sidebar';
import ouApiSidebar from './docs/apis/ou/sidebar';
import registrationApiSidebar from './docs/apis/registration/sidebar';
import resourceApiSidebar from './docs/apis/resource/sidebar';
import roleApiSidebar from './docs/apis/role/sidebar';
import userApiSidebar from './docs/apis/user/sidebar';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: 'guides'}],
  apisSidebar: [
    {
      type: 'category',
      label: 'Applications',
      link: {
        type: 'generated-index',
        title: 'Application',
        description: 'This API is used to manage applications.',
        slug: '/apis/application',
      },
      items: applicationApiSidebar,
    },
    {
      type: 'category',
      label: 'Authentication',
      link: {
        type: 'generated-index',
        title: 'Authentication',
        description: 'This API is used to manage authentication.',
        slug: '/apis/authentication',
      },
      items: authenticationApiSidebar,
    },
    {
      type: 'category',
      label: 'Branding',
      link: {
        type: 'generated-index',
        title: 'Branding',
        description: 'This API is used to manage branding.',
        slug: '/apis/branding',
      },
      items: brandingApiSidebar,
    },
    {
      type: 'category',
      label: 'Flow Execution',
      link: {
        type: 'generated-index',
        title: 'Flow Execution',
        description: 'This API is used to execute flows.',
        slug: '/apis/flow-execution',
      },
      items: flowExecutionApiSidebar,
    },
    {
      type: 'category',
      label: 'Flow Management',
      link: {
        type: 'generated-index',
        title: 'Flow Management',
        description: 'This API is used to manage flows.',
        slug: '/apis/flow-management',
      },
      items: flowManagementApiSidebar,
    },
    {
      type: 'category',
      label: 'Group',
      link: {
        type: 'generated-index',
        title: 'Group',
        description: 'This API is used to manage groups.',
        slug: '/apis/group',
      },
      items: groupApiSidebar,
    },
    {
      type: 'category',
      label: 'Health Check',
      link: {
        type: 'generated-index',
        title: 'Health Check',
        description: 'This API is used to check the health of the system.',
        slug: '/apis/health-check',
      },
      items: healthCheckApiSidebar,
    },
    {
      type: 'category',
      label: 'Internationalization',
      link: {
        type: 'generated-index',
        title: 'Internationalization',
        description: 'This API is used to manage internationalization.',
        slug: '/apis/i18n',
      },
      items: i18nApiSidebar,
    },
    {
      type: 'category',
      label: 'Identity Provider',
      link: {
        type: 'generated-index',
        title: 'Identity Provider',
        description: 'This API is used to manage identity providers.',
        slug: '/apis/idp',
      },
      items: idpApiSidebar,
    },
    {
      type: 'category',
      label: 'Notification Sender',
      link: {
        type: 'generated-index',
        title: 'Notification Sender',
        description: 'This API is used to manage notification senders.',
        slug: '/apis/notification-sender',
      },
      items: notificationSenderApiSidebar,
    },
    {
      type: 'category',
      label: 'Organization Unit',
      link: {
        type: 'generated-index',
        title: 'Organization Unit',
        description: 'This API is used to manage organization units.',
        slug: '/apis/ou',
      },
      items: ouApiSidebar,
    },
    {
      type: 'category',
      label: 'Registration',
      link: {
        type: 'generated-index',
        title: 'Registration',
        description: 'This API is used to manage registration.',
        slug: '/apis/registration',
      },
      items: registrationApiSidebar,
    },
    {
      type: 'category',
      label: 'Resource',
      link: {
        type: 'generated-index',
        title: 'Resource',
        description: 'This API is used to manage resources.',
        slug: '/apis/resource',
      },
      items: resourceApiSidebar,
    },
    {
      type: 'category',
      label: 'Role',
      link: {
        type: 'generated-index',
        title: 'Role',
        description: 'This API is used to manage roles.',
        slug: '/apis/role',
      },
      items: roleApiSidebar,
    },
    {
      type: 'category',
      label: 'User',
      link: {
        type: 'generated-index',
        title: 'User',
        description: 'This API is used to manage users.',
        slug: '/apis/user',
      },
      items: userApiSidebar,
    },
  ],
  communitySidebar: [
    {
      type: 'category',
      label: 'Contributing',
      link: {
        type: 'doc',
        id: 'community/contributing/README',
      },
      items: [
        'community/contributing/problem-definition',
        'community/contributing/design',
        'community/contributing/development',
        {
          type: 'category',
          label: 'Development',
          items: ['community/contributing/development/observability'],
        },
      ],
    },
  ],
};

export default sidebars;
