# Copyright 2025 The ThunderID Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thunderid.fullname" . }}-config-map
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thunderid.labels" . | nindent 4 }}
data:
  deployment.yaml: {{ tpl (.Files.Get "conf/deployment.yaml") . | quote }}
  gate-config.js: {{ tpl (.Files.Get "conf/apps/gate/config.js") . | quote }}
  console-config.js: {{ tpl (.Files.Get "conf/apps/console/config.js") . | quote }}
