# Copyright 2025 The ThunderID Authors
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "thunderid.fullname" . }}-hpa
spec:
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  minReplicas: {{ .Values.deployment.replicaCount }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "thunderid.fullname" . }}-deployment
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.averageUtilizationCPU }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.averageUtilizationMemory }}
{{- end }}
