# Copyright 2025 The ThunderID Authors
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- if eq .Values.ingress.className "nginx" }}
    {{- $annotations := deepCopy .Values.ingress.combinedAnnotations }}
    {{- if .Values.configuration.server.httpOnly }}
    {{- $_ := set $annotations "nginx.ingress.kubernetes.io/backend-protocol" "HTTP" }}
    {{- $_ := unset $annotations "nginx.ingress.kubernetes.io/force-ssl-redirect" }}
    {{- end }}
    {{- toYaml $annotations | nindent 4 }}
    {{- else }}
    {{- toYaml .Values.ingress.customAnnotations | nindent 4 }}
    {{- end }}
  name: {{ include "thunderid.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thunderid.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "thunderid.fullname" .  }}-service
                port:
                  number: {{ .Values.service.port }}
  {{- if not .Values.configuration.server.httpOnly }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname | quote }}
    secretName: {{ .Values.ingress.tlsSecretsName  }}
  {{- end }}
{{- end }}
