# Copyright 2025 The ThunderID Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "thunderid.fullname" . }}-endpoints-reader-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    verbs: ["get", "list"]
    resources: ["endpoints"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "thunderid.fullname" . }}-endpoints-reader-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "thunderid.fullname" . }}-endpoints-reader-role
subjects:
  - kind: ServiceAccount
    name: {{ include "thunderid.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
