# Copyright 2025 The ThunderID Authors
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.setup.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thunderid.fullname" . }}-setup-config-map
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thunderid.labels" . | nindent 4 }}
    app.kubernetes.io/component: setup
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
data:
  deployment.yaml: {{ tpl (.Files.Get "conf/deployment.yaml") . | quote }}
{{- end }}
