// Code generated by i18n-extractor. DO NOT EDIT.
// Run 'make generate_i18n' to regenerate.

/*
 * Copyright (c) 2025, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package core

// defaultMessages contains all i18n keys extracted from source code.
// This map is populated by the i18n extraction script at build time.
// Helper functions for accessing these messages are in helpers.go.
var defaultMessages = map[string]string{
	"error.i18nservice.empty_translations": "Empty translations",
	"error.i18nservice.empty_translations_description": "At least one translation must be provided",
	"error.i18nservice.internal_server_error": "Internal server error",
	"error.i18nservice.internal_server_error_description": "An unexpected error occurred while processing the request",
	"error.i18nservice.invalid_key": "Invalid key format",
	"error.i18nservice.invalid_key_description": "The key can only contain alphanumeric characters, dots, underscores, and hyphens",
	"error.i18nservice.invalid_language": "Invalid language tag format",
	"error.i18nservice.invalid_language_description": "The language tag must follow canonical BCP 47 format (e.g., 'en', 'es', 'fr-CA')",
	"error.i18nservice.invalid_namespace": "Invalid namespace format",
	"error.i18nservice.invalid_namespace_description": "The namespace can only contain alphanumeric characters, underscores, and hyphens",
	"error.i18nservice.invalid_request_description": "The request body is malformed or contains invalid data",
	"error.i18nservice.invalid_request_format": "Invalid request format",
	"error.i18nservice.missing_language": "Missing language code",
	"error.i18nservice.missing_language_description": "Language code is required",
	"error.i18nservice.missing_value": "Missing translation value",
	"error.i18nservice.missing_value_description": "Translation value is required",
	"error.i18nservice.translation_not_found": "Translation not found",
	"error.i18nservice.translation_not_found_description": "The requested translation does not exist for the specified language, namespace, and key",
	"error.immutable_resource.create_operation_not_allowed": "Immutable resource create operation is not allowed",
	"error.immutable_resource.create_operation_not_allowed_description": "Creating immutable resources is not permitted",
	"error.immutable_resource.delete_operation_not_allowed": "Immutable resource delete operation is not allowed",
	"error.immutable_resource.delete_operation_not_allowed_description": "Deleting immutable resources is not permitted",
	"error.immutable_resource.update_operation_not_allowed": "Immutable resource update operation is not allowed",
	"error.immutable_resource.update_operation_not_allowed_description": "Updating immutable resources is not permitted",
}
